"""fix_datetime_format_and_structure

Revision ID: 908497b71282
Revises: 
Create Date: 2026-01-06 22:42:37.722097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '908497b71282'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('estado', postgresql.ENUM('activo', 'bloqueado', name='estado_usuario', schema='acceso'), server_default=sa.text("'bloqueado'::acceso.estado_usuario"), nullable=False),
    sa.Column('imagen', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='acceso'
    )
    op.create_table('chip',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.BigInteger(), nullable=False),
    sa.Column('iccid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('operador', sa.VARCHAR(length=255), nullable=False),
    sa.Column('mb', sa.VARCHAR(length=255), nullable=False),
    sa.Column('activacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('instalacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('adicional', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iccid'),
    sa.UniqueConstraint('numero'),
    schema='administracion'
    )
    op.create_table('cliente',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc'),
    schema='administracion'
    )
    op.create_table('pro',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fact_rel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('adicional', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_table('weather',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fact_rel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('adicional', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_table('permiso',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_module', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['acceso.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'name_module', name='uq_permiso_usuario_modulo'),
    schema='acceso'
    )
    op.create_table('imagen_chips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('image_byte', sa.LargeBinary(), nullable=False),
    sa.Column('chip_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['chip_id'], ['administracion.chip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['administracion.cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'name', name='uq_ubicacion_cliente_name'),
    schema='administracion'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion', schema='administracion')
    op.drop_table('imagen_chips', schema='administracion')
    op.drop_table('permiso', schema='acceso')
    op.drop_table('weather', schema='administracion')
    op.drop_table('pro', schema='administracion')
    op.drop_table('cliente', schema='administracion')
    op.drop_table('chip', schema='administracion')
    op.drop_table('usuario', schema='acceso')
    # ### end Alembic commands ###
