"""Primera version de tablas con integracion redis y websocket

Revision ID: 99ed6ac7e4f0
Revises: 
Create Date: 2026-02-05 07:59:35.157125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99ed6ac7e4f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('estado', postgresql.ENUM('activo', 'bloqueado', name='estado_usuario', schema='acceso'), server_default=sa.text("'bloqueado'::acceso.estado_usuario"), nullable=False),
    sa.Column('imagen', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='acceso'
    )
    op.create_table('chip',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.BigInteger(), nullable=False),
    sa.Column('iccid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('operador', sa.VARCHAR(length=255), nullable=False),
    sa.Column('mb', sa.VARCHAR(length=255), nullable=False),
    sa.Column('activacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('instalacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('adicional', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('imagen1', sa.LargeBinary(), nullable=True),
    sa.Column('imagen2', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iccid'),
    sa.UniqueConstraint('numero'),
    schema='administracion'
    )
    op.create_table('chipservicio',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=15), nullable=False),
    sa.Column('operador', sa.VARCHAR(length=20), nullable=False),
    sa.Column('plan', sa.VARCHAR(length=20), nullable=False),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fact_rel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('adicional', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_table('cliente',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc'),
    schema='administracion'
    )
    op.create_table('pro',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fact_rel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('adicional', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_table('serviciomc',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('servicio', sa.VARCHAR(length=60), nullable=False),
    sa.Column('informe', sa.VARCHAR(length=50), nullable=True),
    sa.Column('certificado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('encargado', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tecnico', sa.VARCHAR(length=100), nullable=True),
    sa.Column('incidencia', sa.VARCHAR(length=400), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_table('weather',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fact_rel', sa.VARCHAR(length=50), nullable=True),
    sa.Column('adicional', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='administracion'
    )
    op.create_table('catalogo_material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medida', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('plimit', sa.BigInteger(), nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=400), nullable=True),
    sa.Column('imagen1', sa.LargeBinary(), nullable=True),
    sa.Column('imagen2', sa.LargeBinary(), nullable=True),
    sa.Column('imagen3', sa.LargeBinary(), nullable=True),
    sa.Column('imagen4', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='almacen'
    )
    op.create_table('catalogo_mercaderia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medida', sa.VARCHAR(length=20), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=False),
    sa.Column('plimit', sa.BigInteger(), nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=400), nullable=True),
    sa.Column('imagen1', sa.LargeBinary(), nullable=True),
    sa.Column('imagen2', sa.LargeBinary(), nullable=True),
    sa.Column('imagen3', sa.LargeBinary(), nullable=True),
    sa.Column('imagen4', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='almacen'
    )
    op.create_table('ingreso_material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.VARCHAR(length=11), nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=200), nullable=False),
    sa.Column('serieNumCP', sa.VARCHAR(length=50), nullable=True),
    sa.Column('serieNumGR', sa.VARCHAR(length=50), nullable=True),
    sa.Column('condicion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('moneda', sa.VARCHAR(length=10), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('uuid_material', sa.VARCHAR(length=40), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medida', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=100), nullable=True),
    sa.Column('serie', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cantidad', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_byte', sa.LargeBinary(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='almacen'
    )
    op.create_table('ingreso_mercaderia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.VARCHAR(length=11), nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=200), nullable=False),
    sa.Column('serieNumCP', sa.VARCHAR(length=50), nullable=True),
    sa.Column('serieNumGR', sa.VARCHAR(length=50), nullable=True),
    sa.Column('condicion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('moneda', sa.VARCHAR(length=10), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('uuid_mercaderia', sa.VARCHAR(length=40), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medida', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=100), nullable=True),
    sa.Column('serie', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cantidad', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_byte', sa.LargeBinary(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ubicacion', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='almacen'
    )
    op.create_table('salida_material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.VARCHAR(length=11), nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=200), nullable=False),
    sa.Column('serieNumGR', sa.VARCHAR(length=50), nullable=True),
    sa.Column('condicion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('adicional', sa.VARCHAR(length=200), nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('uuid_material', sa.VARCHAR(length=40), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medida', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=100), nullable=True),
    sa.Column('moneda', sa.VARCHAR(length=10), nullable=False),
    sa.Column('serie', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cantidad', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_byte', sa.LargeBinary(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='almacen'
    )
    op.create_table('salida_mercaderia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.VARCHAR(length=11), nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=200), nullable=False),
    sa.Column('adicional', sa.VARCHAR(length=200), nullable=True),
    sa.Column('serieNumGR', sa.VARCHAR(length=50), nullable=True),
    sa.Column('condicion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('moneda', sa.VARCHAR(length=10), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('uuid_mercaderia', sa.VARCHAR(length=40), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('marca', sa.VARCHAR(length=100), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('medida', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dimension', sa.VARCHAR(length=100), nullable=True),
    sa.Column('serie', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cantidad', sa.BigInteger(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_byte', sa.LargeBinary(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='almacen'
    )
    op.create_table('clientesinicio',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.VARCHAR(length=11), nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=400), nullable=False),
    sa.Column('dfiscal', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto1', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto2', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto3', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto4', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto5', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro1', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro2', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro3', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro4', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro5', sa.VARCHAR(length=400), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc'),
    schema='gerencia'
    )
    op.create_table('proveedoresinicio',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.VARCHAR(length=11), nullable=False),
    sa.Column('proveedor', sa.VARCHAR(length=400), nullable=False),
    sa.Column('dfiscal', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto1', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto2', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto3', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto4', sa.VARCHAR(length=400), nullable=True),
    sa.Column('contacto5', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro1', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro2', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro3', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro4', sa.VARCHAR(length=400), nullable=True),
    sa.Column('otro5', sa.VARCHAR(length=400), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc'),
    schema='gerencia'
    )
    op.create_table('permiso',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_module', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['acceso.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'name_module', name='uq_permiso_usuario_modulo'),
    schema='acceso'
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['administracion.cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'name', name='uq_ubicacion_cliente_name'),
    schema='administracion'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion', schema='administracion')
    op.drop_table('permiso', schema='acceso')
    op.drop_table('proveedoresinicio', schema='gerencia')
    op.drop_table('clientesinicio', schema='gerencia')
    op.drop_table('salida_mercaderia', schema='almacen')
    op.drop_table('salida_material', schema='almacen')
    op.drop_table('ingreso_mercaderia', schema='almacen')
    op.drop_table('ingreso_material', schema='almacen')
    op.drop_table('catalogo_mercaderia', schema='almacen')
    op.drop_table('catalogo_material', schema='almacen')
    op.drop_table('weather', schema='administracion')
    op.drop_table('serviciomc', schema='administracion')
    op.drop_table('pro', schema='administracion')
    op.drop_table('cliente', schema='administracion')
    op.drop_table('chipservicio', schema='administracion')
    op.drop_table('chip', schema='administracion')
    op.drop_table('usuario', schema='acceso')
    # ### end Alembic commands ###
