/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesoreriaRouteImport } from './routes/tesoreria'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as ContabilidadRouteImport } from './routes/contabilidad'
import { Route as AlmacenRouteImport } from './routes/almacen'
import { Route as AdministracionRouteImport } from './routes/administracion'

const IndexLazyRouteImport = createFileRoute('/')()
const TesoreriaIndexLazyRouteImport = createFileRoute('/tesoreria/')()
const ProduccionIndexLazyRouteImport = createFileRoute('/produccion/')()
const GerenciaIndexLazyRouteImport = createFileRoute('/gerencia/')()
const ContabilidadIndexLazyRouteImport = createFileRoute('/contabilidad/')()
const AlmacenIndexLazyRouteImport = createFileRoute('/almacen/')()
const AdministracionIndexLazyRouteImport = createFileRoute('/administracion/')()
const ProduccionStockLazyRouteImport = createFileRoute('/produccion/stock')()
const GerenciaUsuariosLazyRouteImport = createFileRoute('/gerencia/usuarios')()
const GerenciaOrdenesLazyRouteImport = createFileRoute('/gerencia/ordenes')()
const GerenciaCotizacionesLazyRouteImport = createFileRoute(
  '/gerencia/cotizaciones',
)()
const GerenciaActivosLazyRouteImport = createFileRoute('/gerencia/activos')()
const GerenciaActividadesLazyRouteImport = createFileRoute(
  '/gerencia/actividades',
)()
const AlmacenStockLazyRouteImport = createFileRoute('/almacen/stock')()
const AlmacenSalidasLazyRouteImport = createFileRoute('/almacen/salidas')()
const AlmacenIngresosLazyRouteImport = createFileRoute('/almacen/ingresos')()
const AlmacenCatalogosLazyRouteImport = createFileRoute('/almacen/catalogos')()
const GerenciaCotizacionesIndexLazyRouteImport = createFileRoute(
  '/gerencia/cotizaciones/',
)()
const AdministracionMonitoreoIndexLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/',
)()
const AdministracionListaIndexLazyRouteImport = createFileRoute(
  '/administracion/lista/',
)()
const GerenciaCotizacionesCrearLazyRouteImport = createFileRoute(
  '/gerencia/cotizaciones/crear',
)()
const AdministracionMonitoreoWeatherLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/weather',
)()
const AdministracionMonitoreoServiciosLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/servicios',
)()
const AdministracionMonitoreoProLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/pro',
)()
const AdministracionMonitoreoInicioLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/inicio',
)()
const AdministracionMonitoreoChipsLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/chips',
)()
const AdministracionListaProveedoresLazyRouteImport = createFileRoute(
  '/administracion/lista/proveedores',
)()
const AdministracionListaClientesLazyRouteImport = createFileRoute(
  '/administracion/lista/clientes',
)()
const AdministracionHistorialVentasLazyRouteImport = createFileRoute(
  '/administracion/historial/ventas',
)()
const AdministracionHistorialIndezLazyRouteImport = createFileRoute(
  '/administracion/historial/indez',
)()
const AdministracionHistorialComprasLazyRouteImport = createFileRoute(
  '/administracion/historial/compras',
)()

const TesoreriaRoute = TesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadRoute = ContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenRoute = AlmacenRouteImport.update({
  id: '/almacen',
  path: '/almacen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TesoreriaIndexLazyRoute = TesoreriaIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TesoreriaRoute,
} as any).lazy(() =>
  import('./routes/tesoreria/index.lazy').then((d) => d.Route),
)
const ProduccionIndexLazyRoute = ProduccionIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduccionRoute,
} as any).lazy(() =>
  import('./routes/produccion/index.lazy').then((d) => d.Route),
)
const GerenciaIndexLazyRoute = GerenciaIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/index.lazy').then((d) => d.Route),
)
const ContabilidadIndexLazyRoute = ContabilidadIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContabilidadRoute,
} as any).lazy(() =>
  import('./routes/contabilidad/index.lazy').then((d) => d.Route),
)
const AlmacenIndexLazyRoute = AlmacenIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() => import('./routes/almacen/index.lazy').then((d) => d.Route))
const AdministracionIndexLazyRoute = AdministracionIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministracionRoute,
} as any).lazy(() =>
  import('./routes/administracion/index.lazy').then((d) => d.Route),
)
const ProduccionStockLazyRoute = ProduccionStockLazyRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ProduccionRoute,
} as any).lazy(() =>
  import('./routes/produccion/stock.lazy').then((d) => d.Route),
)
const GerenciaUsuariosLazyRoute = GerenciaUsuariosLazyRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/usuarios.lazy').then((d) => d.Route),
)
const GerenciaOrdenesLazyRoute = GerenciaOrdenesLazyRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/ordenes.lazy').then((d) => d.Route),
)
const GerenciaCotizacionesLazyRoute =
  GerenciaCotizacionesLazyRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => GerenciaRoute,
  } as any).lazy(() =>
    import('./routes/gerencia/cotizaciones.lazy').then((d) => d.Route),
  )
const GerenciaActivosLazyRoute = GerenciaActivosLazyRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/activos.lazy').then((d) => d.Route),
)
const GerenciaActividadesLazyRoute = GerenciaActividadesLazyRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/actividades.lazy').then((d) => d.Route),
)
const AlmacenStockLazyRoute = AlmacenStockLazyRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() => import('./routes/almacen/stock.lazy').then((d) => d.Route))
const AlmacenSalidasLazyRoute = AlmacenSalidasLazyRouteImport.update({
  id: '/salidas',
  path: '/salidas',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() =>
  import('./routes/almacen/salidas.lazy').then((d) => d.Route),
)
const AlmacenIngresosLazyRoute = AlmacenIngresosLazyRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() =>
  import('./routes/almacen/ingresos.lazy').then((d) => d.Route),
)
const AlmacenCatalogosLazyRoute = AlmacenCatalogosLazyRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() =>
  import('./routes/almacen/catalogos.lazy').then((d) => d.Route),
)
const GerenciaCotizacionesIndexLazyRoute =
  GerenciaCotizacionesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GerenciaCotizacionesLazyRoute,
  } as any).lazy(() =>
    import('./routes/gerencia/cotizaciones/index.lazy').then((d) => d.Route),
  )
const AdministracionMonitoreoIndexLazyRoute =
  AdministracionMonitoreoIndexLazyRouteImport.update({
    id: '/monitoreo/',
    path: '/monitoreo/',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/index.lazy').then((d) => d.Route),
  )
const AdministracionListaIndexLazyRoute =
  AdministracionListaIndexLazyRouteImport.update({
    id: '/lista/',
    path: '/lista/',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/lista/index.lazy').then((d) => d.Route),
  )
const GerenciaCotizacionesCrearLazyRoute =
  GerenciaCotizacionesCrearLazyRouteImport.update({
    id: '/crear',
    path: '/crear',
    getParentRoute: () => GerenciaCotizacionesLazyRoute,
  } as any).lazy(() =>
    import('./routes/gerencia/cotizaciones/crear.lazy').then((d) => d.Route),
  )
const AdministracionMonitoreoWeatherLazyRoute =
  AdministracionMonitoreoWeatherLazyRouteImport.update({
    id: '/monitoreo/weather',
    path: '/monitoreo/weather',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/weather.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionMonitoreoServiciosLazyRoute =
  AdministracionMonitoreoServiciosLazyRouteImport.update({
    id: '/monitoreo/servicios',
    path: '/monitoreo/servicios',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/servicios.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionMonitoreoProLazyRoute =
  AdministracionMonitoreoProLazyRouteImport.update({
    id: '/monitoreo/pro',
    path: '/monitoreo/pro',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/pro.lazy').then((d) => d.Route),
  )
const AdministracionMonitoreoInicioLazyRoute =
  AdministracionMonitoreoInicioLazyRouteImport.update({
    id: '/monitoreo/inicio',
    path: '/monitoreo/inicio',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/inicio.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionMonitoreoChipsLazyRoute =
  AdministracionMonitoreoChipsLazyRouteImport.update({
    id: '/monitoreo/chips',
    path: '/monitoreo/chips',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/chips.lazy').then((d) => d.Route),
  )
const AdministracionListaProveedoresLazyRoute =
  AdministracionListaProveedoresLazyRouteImport.update({
    id: '/lista/proveedores',
    path: '/lista/proveedores',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/lista/proveedores.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionListaClientesLazyRoute =
  AdministracionListaClientesLazyRouteImport.update({
    id: '/lista/clientes',
    path: '/lista/clientes',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/lista/clientes.lazy').then((d) => d.Route),
  )
const AdministracionHistorialVentasLazyRoute =
  AdministracionHistorialVentasLazyRouteImport.update({
    id: '/historial/ventas',
    path: '/historial/ventas',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/historial/ventas.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionHistorialIndezLazyRoute =
  AdministracionHistorialIndezLazyRouteImport.update({
    id: '/historial/indez',
    path: '/historial/indez',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/historial/indez.lazy').then((d) => d.Route),
  )
const AdministracionHistorialComprasLazyRoute =
  AdministracionHistorialComprasLazyRouteImport.update({
    id: '/historial/compras',
    path: '/historial/compras',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/historial/compras.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/almacen': typeof AlmacenRouteWithChildren
  '/contabilidad': typeof ContabilidadRouteWithChildren
  '/gerencia': typeof GerenciaRouteWithChildren
  '/produccion': typeof ProduccionRouteWithChildren
  '/tesoreria': typeof TesoreriaRouteWithChildren
  '/almacen/catalogos': typeof AlmacenCatalogosLazyRoute
  '/almacen/ingresos': typeof AlmacenIngresosLazyRoute
  '/almacen/salidas': typeof AlmacenSalidasLazyRoute
  '/almacen/stock': typeof AlmacenStockLazyRoute
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesLazyRouteWithChildren
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/produccion/stock': typeof ProduccionStockLazyRoute
  '/administracion/': typeof AdministracionIndexLazyRoute
  '/almacen/': typeof AlmacenIndexLazyRoute
  '/contabilidad/': typeof ContabilidadIndexLazyRoute
  '/gerencia/': typeof GerenciaIndexLazyRoute
  '/produccion/': typeof ProduccionIndexLazyRoute
  '/tesoreria/': typeof TesoreriaIndexLazyRoute
  '/administracion/historial/compras': typeof AdministracionHistorialComprasLazyRoute
  '/administracion/historial/indez': typeof AdministracionHistorialIndezLazyRoute
  '/administracion/historial/ventas': typeof AdministracionHistorialVentasLazyRoute
  '/administracion/lista/clientes': typeof AdministracionListaClientesLazyRoute
  '/administracion/lista/proveedores': typeof AdministracionListaProveedoresLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoChipsLazyRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoInicioLazyRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoProLazyRoute
  '/administracion/monitoreo/servicios': typeof AdministracionMonitoreoServiciosLazyRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoWeatherLazyRoute
  '/gerencia/cotizaciones/crear': typeof GerenciaCotizacionesCrearLazyRoute
  '/administracion/lista': typeof AdministracionListaIndexLazyRoute
  '/administracion/monitoreo': typeof AdministracionMonitoreoIndexLazyRoute
  '/gerencia/cotizaciones/': typeof GerenciaCotizacionesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/almacen/catalogos': typeof AlmacenCatalogosLazyRoute
  '/almacen/ingresos': typeof AlmacenIngresosLazyRoute
  '/almacen/salidas': typeof AlmacenSalidasLazyRoute
  '/almacen/stock': typeof AlmacenStockLazyRoute
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/produccion/stock': typeof ProduccionStockLazyRoute
  '/administracion': typeof AdministracionIndexLazyRoute
  '/almacen': typeof AlmacenIndexLazyRoute
  '/contabilidad': typeof ContabilidadIndexLazyRoute
  '/gerencia': typeof GerenciaIndexLazyRoute
  '/produccion': typeof ProduccionIndexLazyRoute
  '/tesoreria': typeof TesoreriaIndexLazyRoute
  '/administracion/historial/compras': typeof AdministracionHistorialComprasLazyRoute
  '/administracion/historial/indez': typeof AdministracionHistorialIndezLazyRoute
  '/administracion/historial/ventas': typeof AdministracionHistorialVentasLazyRoute
  '/administracion/lista/clientes': typeof AdministracionListaClientesLazyRoute
  '/administracion/lista/proveedores': typeof AdministracionListaProveedoresLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoChipsLazyRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoInicioLazyRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoProLazyRoute
  '/administracion/monitoreo/servicios': typeof AdministracionMonitoreoServiciosLazyRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoWeatherLazyRoute
  '/gerencia/cotizaciones/crear': typeof GerenciaCotizacionesCrearLazyRoute
  '/administracion/lista': typeof AdministracionListaIndexLazyRoute
  '/administracion/monitoreo': typeof AdministracionMonitoreoIndexLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/almacen': typeof AlmacenRouteWithChildren
  '/contabilidad': typeof ContabilidadRouteWithChildren
  '/gerencia': typeof GerenciaRouteWithChildren
  '/produccion': typeof ProduccionRouteWithChildren
  '/tesoreria': typeof TesoreriaRouteWithChildren
  '/almacen/catalogos': typeof AlmacenCatalogosLazyRoute
  '/almacen/ingresos': typeof AlmacenIngresosLazyRoute
  '/almacen/salidas': typeof AlmacenSalidasLazyRoute
  '/almacen/stock': typeof AlmacenStockLazyRoute
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesLazyRouteWithChildren
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/produccion/stock': typeof ProduccionStockLazyRoute
  '/administracion/': typeof AdministracionIndexLazyRoute
  '/almacen/': typeof AlmacenIndexLazyRoute
  '/contabilidad/': typeof ContabilidadIndexLazyRoute
  '/gerencia/': typeof GerenciaIndexLazyRoute
  '/produccion/': typeof ProduccionIndexLazyRoute
  '/tesoreria/': typeof TesoreriaIndexLazyRoute
  '/administracion/historial/compras': typeof AdministracionHistorialComprasLazyRoute
  '/administracion/historial/indez': typeof AdministracionHistorialIndezLazyRoute
  '/administracion/historial/ventas': typeof AdministracionHistorialVentasLazyRoute
  '/administracion/lista/clientes': typeof AdministracionListaClientesLazyRoute
  '/administracion/lista/proveedores': typeof AdministracionListaProveedoresLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoChipsLazyRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoInicioLazyRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoProLazyRoute
  '/administracion/monitoreo/servicios': typeof AdministracionMonitoreoServiciosLazyRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoWeatherLazyRoute
  '/gerencia/cotizaciones/crear': typeof GerenciaCotizacionesCrearLazyRoute
  '/administracion/lista/': typeof AdministracionListaIndexLazyRoute
  '/administracion/monitoreo/': typeof AdministracionMonitoreoIndexLazyRoute
  '/gerencia/cotizaciones/': typeof GerenciaCotizacionesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/produccion'
    | '/tesoreria'
    | '/almacen/catalogos'
    | '/almacen/ingresos'
    | '/almacen/salidas'
    | '/almacen/stock'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/cotizaciones'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/produccion/stock'
    | '/administracion/'
    | '/almacen/'
    | '/contabilidad/'
    | '/gerencia/'
    | '/produccion/'
    | '/tesoreria/'
    | '/administracion/historial/compras'
    | '/administracion/historial/indez'
    | '/administracion/historial/ventas'
    | '/administracion/lista/clientes'
    | '/administracion/lista/proveedores'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/servicios'
    | '/administracion/monitoreo/weather'
    | '/gerencia/cotizaciones/crear'
    | '/administracion/lista'
    | '/administracion/monitoreo'
    | '/gerencia/cotizaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almacen/catalogos'
    | '/almacen/ingresos'
    | '/almacen/salidas'
    | '/almacen/stock'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/produccion/stock'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/produccion'
    | '/tesoreria'
    | '/administracion/historial/compras'
    | '/administracion/historial/indez'
    | '/administracion/historial/ventas'
    | '/administracion/lista/clientes'
    | '/administracion/lista/proveedores'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/servicios'
    | '/administracion/monitoreo/weather'
    | '/gerencia/cotizaciones/crear'
    | '/administracion/lista'
    | '/administracion/monitoreo'
    | '/gerencia/cotizaciones'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/produccion'
    | '/tesoreria'
    | '/almacen/catalogos'
    | '/almacen/ingresos'
    | '/almacen/salidas'
    | '/almacen/stock'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/cotizaciones'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/produccion/stock'
    | '/administracion/'
    | '/almacen/'
    | '/contabilidad/'
    | '/gerencia/'
    | '/produccion/'
    | '/tesoreria/'
    | '/administracion/historial/compras'
    | '/administracion/historial/indez'
    | '/administracion/historial/ventas'
    | '/administracion/lista/clientes'
    | '/administracion/lista/proveedores'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/servicios'
    | '/administracion/monitoreo/weather'
    | '/gerencia/cotizaciones/crear'
    | '/administracion/lista/'
    | '/administracion/monitoreo/'
    | '/gerencia/cotizaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdministracionRoute: typeof AdministracionRouteWithChildren
  AlmacenRoute: typeof AlmacenRouteWithChildren
  ContabilidadRoute: typeof ContabilidadRouteWithChildren
  GerenciaRoute: typeof GerenciaRouteWithChildren
  ProduccionRoute: typeof ProduccionRouteWithChildren
  TesoreriaRoute: typeof TesoreriaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tesoreria': {
      id: '/tesoreria'
      path: '/tesoreria'
      fullPath: '/tesoreria'
      preLoaderRoute: typeof TesoreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad': {
      id: '/contabilidad'
      path: '/contabilidad'
      fullPath: '/contabilidad'
      preLoaderRoute: typeof ContabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacen': {
      id: '/almacen'
      path: '/almacen'
      fullPath: '/almacen'
      preLoaderRoute: typeof AlmacenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoreria/': {
      id: '/tesoreria/'
      path: '/'
      fullPath: '/tesoreria/'
      preLoaderRoute: typeof TesoreriaIndexLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/produccion/': {
      id: '/produccion/'
      path: '/'
      fullPath: '/produccion/'
      preLoaderRoute: typeof ProduccionIndexLazyRouteImport
      parentRoute: typeof ProduccionRoute
    }
    '/gerencia/': {
      id: '/gerencia/'
      path: '/'
      fullPath: '/gerencia/'
      preLoaderRoute: typeof GerenciaIndexLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/contabilidad/': {
      id: '/contabilidad/'
      path: '/'
      fullPath: '/contabilidad/'
      preLoaderRoute: typeof ContabilidadIndexLazyRouteImport
      parentRoute: typeof ContabilidadRoute
    }
    '/almacen/': {
      id: '/almacen/'
      path: '/'
      fullPath: '/almacen/'
      preLoaderRoute: typeof AlmacenIndexLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/produccion/stock': {
      id: '/produccion/stock'
      path: '/stock'
      fullPath: '/produccion/stock'
      preLoaderRoute: typeof ProduccionStockLazyRouteImport
      parentRoute: typeof ProduccionRoute
    }
    '/gerencia/usuarios': {
      id: '/gerencia/usuarios'
      path: '/usuarios'
      fullPath: '/gerencia/usuarios'
      preLoaderRoute: typeof GerenciaUsuariosLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/ordenes': {
      id: '/gerencia/ordenes'
      path: '/ordenes'
      fullPath: '/gerencia/ordenes'
      preLoaderRoute: typeof GerenciaOrdenesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/cotizaciones': {
      id: '/gerencia/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/gerencia/cotizaciones'
      preLoaderRoute: typeof GerenciaCotizacionesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/activos': {
      id: '/gerencia/activos'
      path: '/activos'
      fullPath: '/gerencia/activos'
      preLoaderRoute: typeof GerenciaActivosLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/actividades': {
      id: '/gerencia/actividades'
      path: '/actividades'
      fullPath: '/gerencia/actividades'
      preLoaderRoute: typeof GerenciaActividadesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/almacen/stock': {
      id: '/almacen/stock'
      path: '/stock'
      fullPath: '/almacen/stock'
      preLoaderRoute: typeof AlmacenStockLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/salidas': {
      id: '/almacen/salidas'
      path: '/salidas'
      fullPath: '/almacen/salidas'
      preLoaderRoute: typeof AlmacenSalidasLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/ingresos': {
      id: '/almacen/ingresos'
      path: '/ingresos'
      fullPath: '/almacen/ingresos'
      preLoaderRoute: typeof AlmacenIngresosLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/catalogos': {
      id: '/almacen/catalogos'
      path: '/catalogos'
      fullPath: '/almacen/catalogos'
      preLoaderRoute: typeof AlmacenCatalogosLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/gerencia/cotizaciones/': {
      id: '/gerencia/cotizaciones/'
      path: '/'
      fullPath: '/gerencia/cotizaciones/'
      preLoaderRoute: typeof GerenciaCotizacionesIndexLazyRouteImport
      parentRoute: typeof GerenciaCotizacionesLazyRoute
    }
    '/administracion/monitoreo/': {
      id: '/administracion/monitoreo/'
      path: '/monitoreo'
      fullPath: '/administracion/monitoreo'
      preLoaderRoute: typeof AdministracionMonitoreoIndexLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/lista/': {
      id: '/administracion/lista/'
      path: '/lista'
      fullPath: '/administracion/lista'
      preLoaderRoute: typeof AdministracionListaIndexLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/gerencia/cotizaciones/crear': {
      id: '/gerencia/cotizaciones/crear'
      path: '/crear'
      fullPath: '/gerencia/cotizaciones/crear'
      preLoaderRoute: typeof GerenciaCotizacionesCrearLazyRouteImport
      parentRoute: typeof GerenciaCotizacionesLazyRoute
    }
    '/administracion/monitoreo/weather': {
      id: '/administracion/monitoreo/weather'
      path: '/monitoreo/weather'
      fullPath: '/administracion/monitoreo/weather'
      preLoaderRoute: typeof AdministracionMonitoreoWeatherLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/servicios': {
      id: '/administracion/monitoreo/servicios'
      path: '/monitoreo/servicios'
      fullPath: '/administracion/monitoreo/servicios'
      preLoaderRoute: typeof AdministracionMonitoreoServiciosLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/pro': {
      id: '/administracion/monitoreo/pro'
      path: '/monitoreo/pro'
      fullPath: '/administracion/monitoreo/pro'
      preLoaderRoute: typeof AdministracionMonitoreoProLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/inicio': {
      id: '/administracion/monitoreo/inicio'
      path: '/monitoreo/inicio'
      fullPath: '/administracion/monitoreo/inicio'
      preLoaderRoute: typeof AdministracionMonitoreoInicioLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/chips': {
      id: '/administracion/monitoreo/chips'
      path: '/monitoreo/chips'
      fullPath: '/administracion/monitoreo/chips'
      preLoaderRoute: typeof AdministracionMonitoreoChipsLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/lista/proveedores': {
      id: '/administracion/lista/proveedores'
      path: '/lista/proveedores'
      fullPath: '/administracion/lista/proveedores'
      preLoaderRoute: typeof AdministracionListaProveedoresLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/lista/clientes': {
      id: '/administracion/lista/clientes'
      path: '/lista/clientes'
      fullPath: '/administracion/lista/clientes'
      preLoaderRoute: typeof AdministracionListaClientesLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/historial/ventas': {
      id: '/administracion/historial/ventas'
      path: '/historial/ventas'
      fullPath: '/administracion/historial/ventas'
      preLoaderRoute: typeof AdministracionHistorialVentasLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/historial/indez': {
      id: '/administracion/historial/indez'
      path: '/historial/indez'
      fullPath: '/administracion/historial/indez'
      preLoaderRoute: typeof AdministracionHistorialIndezLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/historial/compras': {
      id: '/administracion/historial/compras'
      path: '/historial/compras'
      fullPath: '/administracion/historial/compras'
      preLoaderRoute: typeof AdministracionHistorialComprasLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
  }
}

interface AdministracionRouteChildren {
  AdministracionIndexLazyRoute: typeof AdministracionIndexLazyRoute
  AdministracionHistorialComprasLazyRoute: typeof AdministracionHistorialComprasLazyRoute
  AdministracionHistorialIndezLazyRoute: typeof AdministracionHistorialIndezLazyRoute
  AdministracionHistorialVentasLazyRoute: typeof AdministracionHistorialVentasLazyRoute
  AdministracionListaClientesLazyRoute: typeof AdministracionListaClientesLazyRoute
  AdministracionListaProveedoresLazyRoute: typeof AdministracionListaProveedoresLazyRoute
  AdministracionMonitoreoChipsLazyRoute: typeof AdministracionMonitoreoChipsLazyRoute
  AdministracionMonitoreoInicioLazyRoute: typeof AdministracionMonitoreoInicioLazyRoute
  AdministracionMonitoreoProLazyRoute: typeof AdministracionMonitoreoProLazyRoute
  AdministracionMonitoreoServiciosLazyRoute: typeof AdministracionMonitoreoServiciosLazyRoute
  AdministracionMonitoreoWeatherLazyRoute: typeof AdministracionMonitoreoWeatherLazyRoute
  AdministracionListaIndexLazyRoute: typeof AdministracionListaIndexLazyRoute
  AdministracionMonitoreoIndexLazyRoute: typeof AdministracionMonitoreoIndexLazyRoute
}

const AdministracionRouteChildren: AdministracionRouteChildren = {
  AdministracionIndexLazyRoute: AdministracionIndexLazyRoute,
  AdministracionHistorialComprasLazyRoute:
    AdministracionHistorialComprasLazyRoute,
  AdministracionHistorialIndezLazyRoute: AdministracionHistorialIndezLazyRoute,
  AdministracionHistorialVentasLazyRoute:
    AdministracionHistorialVentasLazyRoute,
  AdministracionListaClientesLazyRoute: AdministracionListaClientesLazyRoute,
  AdministracionListaProveedoresLazyRoute:
    AdministracionListaProveedoresLazyRoute,
  AdministracionMonitoreoChipsLazyRoute: AdministracionMonitoreoChipsLazyRoute,
  AdministracionMonitoreoInicioLazyRoute:
    AdministracionMonitoreoInicioLazyRoute,
  AdministracionMonitoreoProLazyRoute: AdministracionMonitoreoProLazyRoute,
  AdministracionMonitoreoServiciosLazyRoute:
    AdministracionMonitoreoServiciosLazyRoute,
  AdministracionMonitoreoWeatherLazyRoute:
    AdministracionMonitoreoWeatherLazyRoute,
  AdministracionListaIndexLazyRoute: AdministracionListaIndexLazyRoute,
  AdministracionMonitoreoIndexLazyRoute: AdministracionMonitoreoIndexLazyRoute,
}

const AdministracionRouteWithChildren = AdministracionRoute._addFileChildren(
  AdministracionRouteChildren,
)

interface AlmacenRouteChildren {
  AlmacenCatalogosLazyRoute: typeof AlmacenCatalogosLazyRoute
  AlmacenIngresosLazyRoute: typeof AlmacenIngresosLazyRoute
  AlmacenSalidasLazyRoute: typeof AlmacenSalidasLazyRoute
  AlmacenStockLazyRoute: typeof AlmacenStockLazyRoute
  AlmacenIndexLazyRoute: typeof AlmacenIndexLazyRoute
}

const AlmacenRouteChildren: AlmacenRouteChildren = {
  AlmacenCatalogosLazyRoute: AlmacenCatalogosLazyRoute,
  AlmacenIngresosLazyRoute: AlmacenIngresosLazyRoute,
  AlmacenSalidasLazyRoute: AlmacenSalidasLazyRoute,
  AlmacenStockLazyRoute: AlmacenStockLazyRoute,
  AlmacenIndexLazyRoute: AlmacenIndexLazyRoute,
}

const AlmacenRouteWithChildren =
  AlmacenRoute._addFileChildren(AlmacenRouteChildren)

interface ContabilidadRouteChildren {
  ContabilidadIndexLazyRoute: typeof ContabilidadIndexLazyRoute
}

const ContabilidadRouteChildren: ContabilidadRouteChildren = {
  ContabilidadIndexLazyRoute: ContabilidadIndexLazyRoute,
}

const ContabilidadRouteWithChildren = ContabilidadRoute._addFileChildren(
  ContabilidadRouteChildren,
)

interface GerenciaCotizacionesLazyRouteChildren {
  GerenciaCotizacionesCrearLazyRoute: typeof GerenciaCotizacionesCrearLazyRoute
  GerenciaCotizacionesIndexLazyRoute: typeof GerenciaCotizacionesIndexLazyRoute
}

const GerenciaCotizacionesLazyRouteChildren: GerenciaCotizacionesLazyRouteChildren =
  {
    GerenciaCotizacionesCrearLazyRoute: GerenciaCotizacionesCrearLazyRoute,
    GerenciaCotizacionesIndexLazyRoute: GerenciaCotizacionesIndexLazyRoute,
  }

const GerenciaCotizacionesLazyRouteWithChildren =
  GerenciaCotizacionesLazyRoute._addFileChildren(
    GerenciaCotizacionesLazyRouteChildren,
  )

interface GerenciaRouteChildren {
  GerenciaActividadesLazyRoute: typeof GerenciaActividadesLazyRoute
  GerenciaActivosLazyRoute: typeof GerenciaActivosLazyRoute
  GerenciaCotizacionesLazyRoute: typeof GerenciaCotizacionesLazyRouteWithChildren
  GerenciaOrdenesLazyRoute: typeof GerenciaOrdenesLazyRoute
  GerenciaUsuariosLazyRoute: typeof GerenciaUsuariosLazyRoute
  GerenciaIndexLazyRoute: typeof GerenciaIndexLazyRoute
}

const GerenciaRouteChildren: GerenciaRouteChildren = {
  GerenciaActividadesLazyRoute: GerenciaActividadesLazyRoute,
  GerenciaActivosLazyRoute: GerenciaActivosLazyRoute,
  GerenciaCotizacionesLazyRoute: GerenciaCotizacionesLazyRouteWithChildren,
  GerenciaOrdenesLazyRoute: GerenciaOrdenesLazyRoute,
  GerenciaUsuariosLazyRoute: GerenciaUsuariosLazyRoute,
  GerenciaIndexLazyRoute: GerenciaIndexLazyRoute,
}

const GerenciaRouteWithChildren = GerenciaRoute._addFileChildren(
  GerenciaRouteChildren,
)

interface ProduccionRouteChildren {
  ProduccionStockLazyRoute: typeof ProduccionStockLazyRoute
  ProduccionIndexLazyRoute: typeof ProduccionIndexLazyRoute
}

const ProduccionRouteChildren: ProduccionRouteChildren = {
  ProduccionStockLazyRoute: ProduccionStockLazyRoute,
  ProduccionIndexLazyRoute: ProduccionIndexLazyRoute,
}

const ProduccionRouteWithChildren = ProduccionRoute._addFileChildren(
  ProduccionRouteChildren,
)

interface TesoreriaRouteChildren {
  TesoreriaIndexLazyRoute: typeof TesoreriaIndexLazyRoute
}

const TesoreriaRouteChildren: TesoreriaRouteChildren = {
  TesoreriaIndexLazyRoute: TesoreriaIndexLazyRoute,
}

const TesoreriaRouteWithChildren = TesoreriaRoute._addFileChildren(
  TesoreriaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdministracionRoute: AdministracionRouteWithChildren,
  AlmacenRoute: AlmacenRouteWithChildren,
  ContabilidadRoute: ContabilidadRouteWithChildren,
  GerenciaRoute: GerenciaRouteWithChildren,
  ProduccionRoute: ProduccionRouteWithChildren,
  TesoreriaRoute: TesoreriaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
