/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesoreriaRouteImport } from './routes/tesoreria'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as ContabilidadRouteImport } from './routes/contabilidad'
import { Route as AlmacenRouteImport } from './routes/almacen'
import { Route as AdministracionRouteImport } from './routes/administracion'
import { Route as TesoreriaPagarIndexRouteImport } from './routes/tesoreria/pagar/index'
import { Route as AdministracionMonitoreoIndexRouteImport } from './routes/administracion/monitoreo/index'
import { Route as TesoreriaPagarLayoutRouteImport } from './routes/tesoreria/pagar/_layout'
import { Route as AdministracionMonitoreoLayoutRouteImport } from './routes/administracion/monitoreo/_layout'
import { Route as TesoreriaPagarLayoutProveedoresRouteImport } from './routes/tesoreria/pagar/_layout.proveedores'
import { Route as TesoreriaPagarLayoutMensualesRouteImport } from './routes/tesoreria/pagar/_layout.mensuales'
import { Route as TesoreriaPagarLayoutEventualesRouteImport } from './routes/tesoreria/pagar/_layout.eventuales'
import { Route as AdministracionMonitoreoLayoutWeatherRouteImport } from './routes/administracion/monitoreo/_layout.weather'
import { Route as AdministracionMonitoreoLayoutServiciosRouteImport } from './routes/administracion/monitoreo/_layout.servicios'
import { Route as AdministracionMonitoreoLayoutProRouteImport } from './routes/administracion/monitoreo/_layout.pro'
import { Route as AdministracionMonitoreoLayoutInicioRouteImport } from './routes/administracion/monitoreo/_layout.inicio'
import { Route as AdministracionMonitoreoLayoutChipsRouteImport } from './routes/administracion/monitoreo/_layout.chips'

const IndexLazyRouteImport = createFileRoute('/')()
const TesoreriaPagarRouteImport = createFileRoute('/tesoreria/pagar')()
const AdministracionMonitoreoRouteImport = createFileRoute(
  '/administracion/monitoreo',
)()
const TesoreriaIndexLazyRouteImport = createFileRoute('/tesoreria/')()
const ProduccionIndexLazyRouteImport = createFileRoute('/produccion/')()
const GerenciaIndexLazyRouteImport = createFileRoute('/gerencia/')()
const ContabilidadIndexLazyRouteImport = createFileRoute('/contabilidad/')()
const AlmacenIndexLazyRouteImport = createFileRoute('/almacen/')()
const AdministracionIndexLazyRouteImport = createFileRoute('/administracion/')()
const TesoreriaCobrarLazyRouteImport = createFileRoute('/tesoreria/cobrar')()
const ProduccionStockLazyRouteImport = createFileRoute('/produccion/stock')()
const GerenciaUsuariosLazyRouteImport = createFileRoute('/gerencia/usuarios')()
const GerenciaOrdenesLazyRouteImport = createFileRoute('/gerencia/ordenes')()
const GerenciaCotizacionesLazyRouteImport = createFileRoute(
  '/gerencia/cotizaciones',
)()
const GerenciaActivosLazyRouteImport = createFileRoute('/gerencia/activos')()
const GerenciaActividadesLazyRouteImport = createFileRoute(
  '/gerencia/actividades',
)()
const ContabilidadVentasLazyRouteImport = createFileRoute(
  '/contabilidad/ventas',
)()
const ContabilidadComprasLazyRouteImport = createFileRoute(
  '/contabilidad/compras',
)()
const AlmacenStockLazyRouteImport = createFileRoute('/almacen/stock')()
const AlmacenSalidasLazyRouteImport = createFileRoute('/almacen/salidas')()
const AlmacenIngresosLazyRouteImport = createFileRoute('/almacen/ingresos')()
const AlmacenCatalogosLazyRouteImport = createFileRoute('/almacen/catalogos')()
const AdministracionActivosLazyRouteImport = createFileRoute(
  '/administracion/activos',
)()
const TesoreriaMovimientoIndexLazyRouteImport = createFileRoute(
  '/tesoreria/movimiento/',
)()
const GerenciaCotizacionesIndexLazyRouteImport = createFileRoute(
  '/gerencia/cotizaciones/',
)()
const AdministracionListaIndexLazyRouteImport = createFileRoute(
  '/administracion/lista/',
)()
const TesoreriaMovimientoSolesLazyRouteImport = createFileRoute(
  '/tesoreria/movimiento/soles',
)()
const TesoreriaMovimientoDolaresLazyRouteImport = createFileRoute(
  '/tesoreria/movimiento/dolares',
)()
const TesoreriaMovimientoCajaLazyRouteImport = createFileRoute(
  '/tesoreria/movimiento/caja',
)()
const GerenciaCotizacionesCrearLazyRouteImport = createFileRoute(
  '/gerencia/cotizaciones/crear',
)()
const AdministracionListaProveedoresLazyRouteImport = createFileRoute(
  '/administracion/lista/proveedores',
)()
const AdministracionListaClientesLazyRouteImport = createFileRoute(
  '/administracion/lista/clientes',
)()
const AdministracionHistorialVentasLazyRouteImport = createFileRoute(
  '/administracion/historial/ventas',
)()
const AdministracionHistorialIndezLazyRouteImport = createFileRoute(
  '/administracion/historial/indez',
)()
const AdministracionHistorialComprasLazyRouteImport = createFileRoute(
  '/administracion/historial/compras',
)()

const TesoreriaRoute = TesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadRoute = ContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenRoute = AlmacenRouteImport.update({
  id: '/almacen',
  path: '/almacen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TesoreriaPagarRoute = TesoreriaPagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => TesoreriaRoute,
} as any)
const AdministracionMonitoreoRoute = AdministracionMonitoreoRouteImport.update({
  id: '/monitoreo',
  path: '/monitoreo',
  getParentRoute: () => AdministracionRoute,
} as any)
const TesoreriaIndexLazyRoute = TesoreriaIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TesoreriaRoute,
} as any).lazy(() =>
  import('./routes/tesoreria/index.lazy').then((d) => d.Route),
)
const ProduccionIndexLazyRoute = ProduccionIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProduccionRoute,
} as any).lazy(() =>
  import('./routes/produccion/index.lazy').then((d) => d.Route),
)
const GerenciaIndexLazyRoute = GerenciaIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/index.lazy').then((d) => d.Route),
)
const ContabilidadIndexLazyRoute = ContabilidadIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContabilidadRoute,
} as any).lazy(() =>
  import('./routes/contabilidad/index.lazy').then((d) => d.Route),
)
const AlmacenIndexLazyRoute = AlmacenIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() => import('./routes/almacen/index.lazy').then((d) => d.Route))
const AdministracionIndexLazyRoute = AdministracionIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministracionRoute,
} as any).lazy(() =>
  import('./routes/administracion/index.lazy').then((d) => d.Route),
)
const TesoreriaCobrarLazyRoute = TesoreriaCobrarLazyRouteImport.update({
  id: '/cobrar',
  path: '/cobrar',
  getParentRoute: () => TesoreriaRoute,
} as any).lazy(() =>
  import('./routes/tesoreria/cobrar.lazy').then((d) => d.Route),
)
const ProduccionStockLazyRoute = ProduccionStockLazyRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => ProduccionRoute,
} as any).lazy(() =>
  import('./routes/produccion/stock.lazy').then((d) => d.Route),
)
const GerenciaUsuariosLazyRoute = GerenciaUsuariosLazyRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/usuarios.lazy').then((d) => d.Route),
)
const GerenciaOrdenesLazyRoute = GerenciaOrdenesLazyRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/ordenes.lazy').then((d) => d.Route),
)
const GerenciaCotizacionesLazyRoute =
  GerenciaCotizacionesLazyRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => GerenciaRoute,
  } as any).lazy(() =>
    import('./routes/gerencia/cotizaciones.lazy').then((d) => d.Route),
  )
const GerenciaActivosLazyRoute = GerenciaActivosLazyRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/activos.lazy').then((d) => d.Route),
)
const GerenciaActividadesLazyRoute = GerenciaActividadesLazyRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/actividades.lazy').then((d) => d.Route),
)
const ContabilidadVentasLazyRoute = ContabilidadVentasLazyRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => ContabilidadRoute,
} as any).lazy(() =>
  import('./routes/contabilidad/ventas.lazy').then((d) => d.Route),
)
const ContabilidadComprasLazyRoute = ContabilidadComprasLazyRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => ContabilidadRoute,
} as any).lazy(() =>
  import('./routes/contabilidad/compras.lazy').then((d) => d.Route),
)
const AlmacenStockLazyRoute = AlmacenStockLazyRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() => import('./routes/almacen/stock.lazy').then((d) => d.Route))
const AlmacenSalidasLazyRoute = AlmacenSalidasLazyRouteImport.update({
  id: '/salidas',
  path: '/salidas',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() =>
  import('./routes/almacen/salidas.lazy').then((d) => d.Route),
)
const AlmacenIngresosLazyRoute = AlmacenIngresosLazyRouteImport.update({
  id: '/ingresos',
  path: '/ingresos',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() =>
  import('./routes/almacen/ingresos.lazy').then((d) => d.Route),
)
const AlmacenCatalogosLazyRoute = AlmacenCatalogosLazyRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() =>
  import('./routes/almacen/catalogos.lazy').then((d) => d.Route),
)
const AdministracionActivosLazyRoute =
  AdministracionActivosLazyRouteImport.update({
    id: '/activos',
    path: '/activos',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/activos.lazy').then((d) => d.Route),
  )
const TesoreriaMovimientoIndexLazyRoute =
  TesoreriaMovimientoIndexLazyRouteImport.update({
    id: '/movimiento/',
    path: '/movimiento/',
    getParentRoute: () => TesoreriaRoute,
  } as any).lazy(() =>
    import('./routes/tesoreria/movimiento/index.lazy').then((d) => d.Route),
  )
const GerenciaCotizacionesIndexLazyRoute =
  GerenciaCotizacionesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GerenciaCotizacionesLazyRoute,
  } as any).lazy(() =>
    import('./routes/gerencia/cotizaciones/index.lazy').then((d) => d.Route),
  )
const AdministracionListaIndexLazyRoute =
  AdministracionListaIndexLazyRouteImport.update({
    id: '/lista/',
    path: '/lista/',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/lista/index.lazy').then((d) => d.Route),
  )
const TesoreriaPagarIndexRoute = TesoreriaPagarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TesoreriaPagarRoute,
} as any)
const AdministracionMonitoreoIndexRoute =
  AdministracionMonitoreoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdministracionMonitoreoRoute,
  } as any)
const TesoreriaMovimientoSolesLazyRoute =
  TesoreriaMovimientoSolesLazyRouteImport.update({
    id: '/movimiento/soles',
    path: '/movimiento/soles',
    getParentRoute: () => TesoreriaRoute,
  } as any).lazy(() =>
    import('./routes/tesoreria/movimiento/soles.lazy').then((d) => d.Route),
  )
const TesoreriaMovimientoDolaresLazyRoute =
  TesoreriaMovimientoDolaresLazyRouteImport.update({
    id: '/movimiento/dolares',
    path: '/movimiento/dolares',
    getParentRoute: () => TesoreriaRoute,
  } as any).lazy(() =>
    import('./routes/tesoreria/movimiento/dolares.lazy').then((d) => d.Route),
  )
const TesoreriaMovimientoCajaLazyRoute =
  TesoreriaMovimientoCajaLazyRouteImport.update({
    id: '/movimiento/caja',
    path: '/movimiento/caja',
    getParentRoute: () => TesoreriaRoute,
  } as any).lazy(() =>
    import('./routes/tesoreria/movimiento/caja.lazy').then((d) => d.Route),
  )
const GerenciaCotizacionesCrearLazyRoute =
  GerenciaCotizacionesCrearLazyRouteImport.update({
    id: '/crear',
    path: '/crear',
    getParentRoute: () => GerenciaCotizacionesLazyRoute,
  } as any).lazy(() =>
    import('./routes/gerencia/cotizaciones/crear.lazy').then((d) => d.Route),
  )
const AdministracionListaProveedoresLazyRoute =
  AdministracionListaProveedoresLazyRouteImport.update({
    id: '/lista/proveedores',
    path: '/lista/proveedores',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/lista/proveedores.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionListaClientesLazyRoute =
  AdministracionListaClientesLazyRouteImport.update({
    id: '/lista/clientes',
    path: '/lista/clientes',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/lista/clientes.lazy').then((d) => d.Route),
  )
const AdministracionHistorialVentasLazyRoute =
  AdministracionHistorialVentasLazyRouteImport.update({
    id: '/historial/ventas',
    path: '/historial/ventas',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/historial/ventas.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionHistorialIndezLazyRoute =
  AdministracionHistorialIndezLazyRouteImport.update({
    id: '/historial/indez',
    path: '/historial/indez',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/historial/indez.lazy').then((d) => d.Route),
  )
const AdministracionHistorialComprasLazyRoute =
  AdministracionHistorialComprasLazyRouteImport.update({
    id: '/historial/compras',
    path: '/historial/compras',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/historial/compras.lazy').then(
      (d) => d.Route,
    ),
  )
const TesoreriaPagarLayoutRoute = TesoreriaPagarLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => TesoreriaPagarRoute,
} as any)
const AdministracionMonitoreoLayoutRoute =
  AdministracionMonitoreoLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AdministracionMonitoreoRoute,
  } as any)
const TesoreriaPagarLayoutProveedoresRoute =
  TesoreriaPagarLayoutProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => TesoreriaPagarLayoutRoute,
  } as any)
const TesoreriaPagarLayoutMensualesRoute =
  TesoreriaPagarLayoutMensualesRouteImport.update({
    id: '/mensuales',
    path: '/mensuales',
    getParentRoute: () => TesoreriaPagarLayoutRoute,
  } as any)
const TesoreriaPagarLayoutEventualesRoute =
  TesoreriaPagarLayoutEventualesRouteImport.update({
    id: '/eventuales',
    path: '/eventuales',
    getParentRoute: () => TesoreriaPagarLayoutRoute,
  } as any)
const AdministracionMonitoreoLayoutWeatherRoute =
  AdministracionMonitoreoLayoutWeatherRouteImport.update({
    id: '/weather',
    path: '/weather',
    getParentRoute: () => AdministracionMonitoreoLayoutRoute,
  } as any)
const AdministracionMonitoreoLayoutServiciosRoute =
  AdministracionMonitoreoLayoutServiciosRouteImport.update({
    id: '/servicios',
    path: '/servicios',
    getParentRoute: () => AdministracionMonitoreoLayoutRoute,
  } as any)
const AdministracionMonitoreoLayoutProRoute =
  AdministracionMonitoreoLayoutProRouteImport.update({
    id: '/pro',
    path: '/pro',
    getParentRoute: () => AdministracionMonitoreoLayoutRoute,
  } as any)
const AdministracionMonitoreoLayoutInicioRoute =
  AdministracionMonitoreoLayoutInicioRouteImport.update({
    id: '/inicio',
    path: '/inicio',
    getParentRoute: () => AdministracionMonitoreoLayoutRoute,
  } as any)
const AdministracionMonitoreoLayoutChipsRoute =
  AdministracionMonitoreoLayoutChipsRouteImport.update({
    id: '/chips',
    path: '/chips',
    getParentRoute: () => AdministracionMonitoreoLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/almacen': typeof AlmacenRouteWithChildren
  '/contabilidad': typeof ContabilidadRouteWithChildren
  '/gerencia': typeof GerenciaRouteWithChildren
  '/produccion': typeof ProduccionRouteWithChildren
  '/tesoreria': typeof TesoreriaRouteWithChildren
  '/administracion/activos': typeof AdministracionActivosLazyRoute
  '/almacen/catalogos': typeof AlmacenCatalogosLazyRoute
  '/almacen/ingresos': typeof AlmacenIngresosLazyRoute
  '/almacen/salidas': typeof AlmacenSalidasLazyRoute
  '/almacen/stock': typeof AlmacenStockLazyRoute
  '/contabilidad/compras': typeof ContabilidadComprasLazyRoute
  '/contabilidad/ventas': typeof ContabilidadVentasLazyRoute
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesLazyRouteWithChildren
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/produccion/stock': typeof ProduccionStockLazyRoute
  '/tesoreria/cobrar': typeof TesoreriaCobrarLazyRoute
  '/administracion/': typeof AdministracionIndexLazyRoute
  '/almacen/': typeof AlmacenIndexLazyRoute
  '/contabilidad/': typeof ContabilidadIndexLazyRoute
  '/gerencia/': typeof GerenciaIndexLazyRoute
  '/produccion/': typeof ProduccionIndexLazyRoute
  '/tesoreria/': typeof TesoreriaIndexLazyRoute
  '/administracion/monitoreo': typeof AdministracionMonitoreoLayoutRouteWithChildren
  '/tesoreria/pagar': typeof TesoreriaPagarLayoutRouteWithChildren
  '/administracion/historial/compras': typeof AdministracionHistorialComprasLazyRoute
  '/administracion/historial/indez': typeof AdministracionHistorialIndezLazyRoute
  '/administracion/historial/ventas': typeof AdministracionHistorialVentasLazyRoute
  '/administracion/lista/clientes': typeof AdministracionListaClientesLazyRoute
  '/administracion/lista/proveedores': typeof AdministracionListaProveedoresLazyRoute
  '/gerencia/cotizaciones/crear': typeof GerenciaCotizacionesCrearLazyRoute
  '/tesoreria/movimiento/caja': typeof TesoreriaMovimientoCajaLazyRoute
  '/tesoreria/movimiento/dolares': typeof TesoreriaMovimientoDolaresLazyRoute
  '/tesoreria/movimiento/soles': typeof TesoreriaMovimientoSolesLazyRoute
  '/administracion/monitoreo/': typeof AdministracionMonitoreoIndexRoute
  '/tesoreria/pagar/': typeof TesoreriaPagarIndexRoute
  '/administracion/lista': typeof AdministracionListaIndexLazyRoute
  '/gerencia/cotizaciones/': typeof GerenciaCotizacionesIndexLazyRoute
  '/tesoreria/movimiento': typeof TesoreriaMovimientoIndexLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoLayoutChipsRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoLayoutInicioRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoLayoutProRoute
  '/administracion/monitoreo/servicios': typeof AdministracionMonitoreoLayoutServiciosRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoLayoutWeatherRoute
  '/tesoreria/pagar/eventuales': typeof TesoreriaPagarLayoutEventualesRoute
  '/tesoreria/pagar/mensuales': typeof TesoreriaPagarLayoutMensualesRoute
  '/tesoreria/pagar/proveedores': typeof TesoreriaPagarLayoutProveedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/administracion/activos': typeof AdministracionActivosLazyRoute
  '/almacen/catalogos': typeof AlmacenCatalogosLazyRoute
  '/almacen/ingresos': typeof AlmacenIngresosLazyRoute
  '/almacen/salidas': typeof AlmacenSalidasLazyRoute
  '/almacen/stock': typeof AlmacenStockLazyRoute
  '/contabilidad/compras': typeof ContabilidadComprasLazyRoute
  '/contabilidad/ventas': typeof ContabilidadVentasLazyRoute
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/produccion/stock': typeof ProduccionStockLazyRoute
  '/tesoreria/cobrar': typeof TesoreriaCobrarLazyRoute
  '/administracion': typeof AdministracionIndexLazyRoute
  '/almacen': typeof AlmacenIndexLazyRoute
  '/contabilidad': typeof ContabilidadIndexLazyRoute
  '/gerencia': typeof GerenciaIndexLazyRoute
  '/produccion': typeof ProduccionIndexLazyRoute
  '/tesoreria': typeof TesoreriaIndexLazyRoute
  '/administracion/monitoreo': typeof AdministracionMonitoreoIndexRoute
  '/tesoreria/pagar': typeof TesoreriaPagarIndexRoute
  '/administracion/historial/compras': typeof AdministracionHistorialComprasLazyRoute
  '/administracion/historial/indez': typeof AdministracionHistorialIndezLazyRoute
  '/administracion/historial/ventas': typeof AdministracionHistorialVentasLazyRoute
  '/administracion/lista/clientes': typeof AdministracionListaClientesLazyRoute
  '/administracion/lista/proveedores': typeof AdministracionListaProveedoresLazyRoute
  '/gerencia/cotizaciones/crear': typeof GerenciaCotizacionesCrearLazyRoute
  '/tesoreria/movimiento/caja': typeof TesoreriaMovimientoCajaLazyRoute
  '/tesoreria/movimiento/dolares': typeof TesoreriaMovimientoDolaresLazyRoute
  '/tesoreria/movimiento/soles': typeof TesoreriaMovimientoSolesLazyRoute
  '/administracion/lista': typeof AdministracionListaIndexLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesIndexLazyRoute
  '/tesoreria/movimiento': typeof TesoreriaMovimientoIndexLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoLayoutChipsRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoLayoutInicioRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoLayoutProRoute
  '/administracion/monitoreo/servicios': typeof AdministracionMonitoreoLayoutServiciosRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoLayoutWeatherRoute
  '/tesoreria/pagar/eventuales': typeof TesoreriaPagarLayoutEventualesRoute
  '/tesoreria/pagar/mensuales': typeof TesoreriaPagarLayoutMensualesRoute
  '/tesoreria/pagar/proveedores': typeof TesoreriaPagarLayoutProveedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/almacen': typeof AlmacenRouteWithChildren
  '/contabilidad': typeof ContabilidadRouteWithChildren
  '/gerencia': typeof GerenciaRouteWithChildren
  '/produccion': typeof ProduccionRouteWithChildren
  '/tesoreria': typeof TesoreriaRouteWithChildren
  '/administracion/activos': typeof AdministracionActivosLazyRoute
  '/almacen/catalogos': typeof AlmacenCatalogosLazyRoute
  '/almacen/ingresos': typeof AlmacenIngresosLazyRoute
  '/almacen/salidas': typeof AlmacenSalidasLazyRoute
  '/almacen/stock': typeof AlmacenStockLazyRoute
  '/contabilidad/compras': typeof ContabilidadComprasLazyRoute
  '/contabilidad/ventas': typeof ContabilidadVentasLazyRoute
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesLazyRouteWithChildren
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/produccion/stock': typeof ProduccionStockLazyRoute
  '/tesoreria/cobrar': typeof TesoreriaCobrarLazyRoute
  '/administracion/': typeof AdministracionIndexLazyRoute
  '/almacen/': typeof AlmacenIndexLazyRoute
  '/contabilidad/': typeof ContabilidadIndexLazyRoute
  '/gerencia/': typeof GerenciaIndexLazyRoute
  '/produccion/': typeof ProduccionIndexLazyRoute
  '/tesoreria/': typeof TesoreriaIndexLazyRoute
  '/administracion/monitoreo': typeof AdministracionMonitoreoRouteWithChildren
  '/administracion/monitoreo/_layout': typeof AdministracionMonitoreoLayoutRouteWithChildren
  '/tesoreria/pagar': typeof TesoreriaPagarRouteWithChildren
  '/tesoreria/pagar/_layout': typeof TesoreriaPagarLayoutRouteWithChildren
  '/administracion/historial/compras': typeof AdministracionHistorialComprasLazyRoute
  '/administracion/historial/indez': typeof AdministracionHistorialIndezLazyRoute
  '/administracion/historial/ventas': typeof AdministracionHistorialVentasLazyRoute
  '/administracion/lista/clientes': typeof AdministracionListaClientesLazyRoute
  '/administracion/lista/proveedores': typeof AdministracionListaProveedoresLazyRoute
  '/gerencia/cotizaciones/crear': typeof GerenciaCotizacionesCrearLazyRoute
  '/tesoreria/movimiento/caja': typeof TesoreriaMovimientoCajaLazyRoute
  '/tesoreria/movimiento/dolares': typeof TesoreriaMovimientoDolaresLazyRoute
  '/tesoreria/movimiento/soles': typeof TesoreriaMovimientoSolesLazyRoute
  '/administracion/monitoreo/': typeof AdministracionMonitoreoIndexRoute
  '/tesoreria/pagar/': typeof TesoreriaPagarIndexRoute
  '/administracion/lista/': typeof AdministracionListaIndexLazyRoute
  '/gerencia/cotizaciones/': typeof GerenciaCotizacionesIndexLazyRoute
  '/tesoreria/movimiento/': typeof TesoreriaMovimientoIndexLazyRoute
  '/administracion/monitoreo/_layout/chips': typeof AdministracionMonitoreoLayoutChipsRoute
  '/administracion/monitoreo/_layout/inicio': typeof AdministracionMonitoreoLayoutInicioRoute
  '/administracion/monitoreo/_layout/pro': typeof AdministracionMonitoreoLayoutProRoute
  '/administracion/monitoreo/_layout/servicios': typeof AdministracionMonitoreoLayoutServiciosRoute
  '/administracion/monitoreo/_layout/weather': typeof AdministracionMonitoreoLayoutWeatherRoute
  '/tesoreria/pagar/_layout/eventuales': typeof TesoreriaPagarLayoutEventualesRoute
  '/tesoreria/pagar/_layout/mensuales': typeof TesoreriaPagarLayoutMensualesRoute
  '/tesoreria/pagar/_layout/proveedores': typeof TesoreriaPagarLayoutProveedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/produccion'
    | '/tesoreria'
    | '/administracion/activos'
    | '/almacen/catalogos'
    | '/almacen/ingresos'
    | '/almacen/salidas'
    | '/almacen/stock'
    | '/contabilidad/compras'
    | '/contabilidad/ventas'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/cotizaciones'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/produccion/stock'
    | '/tesoreria/cobrar'
    | '/administracion/'
    | '/almacen/'
    | '/contabilidad/'
    | '/gerencia/'
    | '/produccion/'
    | '/tesoreria/'
    | '/administracion/monitoreo'
    | '/tesoreria/pagar'
    | '/administracion/historial/compras'
    | '/administracion/historial/indez'
    | '/administracion/historial/ventas'
    | '/administracion/lista/clientes'
    | '/administracion/lista/proveedores'
    | '/gerencia/cotizaciones/crear'
    | '/tesoreria/movimiento/caja'
    | '/tesoreria/movimiento/dolares'
    | '/tesoreria/movimiento/soles'
    | '/administracion/monitoreo/'
    | '/tesoreria/pagar/'
    | '/administracion/lista'
    | '/gerencia/cotizaciones/'
    | '/tesoreria/movimiento'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/servicios'
    | '/administracion/monitoreo/weather'
    | '/tesoreria/pagar/eventuales'
    | '/tesoreria/pagar/mensuales'
    | '/tesoreria/pagar/proveedores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracion/activos'
    | '/almacen/catalogos'
    | '/almacen/ingresos'
    | '/almacen/salidas'
    | '/almacen/stock'
    | '/contabilidad/compras'
    | '/contabilidad/ventas'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/produccion/stock'
    | '/tesoreria/cobrar'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/produccion'
    | '/tesoreria'
    | '/administracion/monitoreo'
    | '/tesoreria/pagar'
    | '/administracion/historial/compras'
    | '/administracion/historial/indez'
    | '/administracion/historial/ventas'
    | '/administracion/lista/clientes'
    | '/administracion/lista/proveedores'
    | '/gerencia/cotizaciones/crear'
    | '/tesoreria/movimiento/caja'
    | '/tesoreria/movimiento/dolares'
    | '/tesoreria/movimiento/soles'
    | '/administracion/lista'
    | '/gerencia/cotizaciones'
    | '/tesoreria/movimiento'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/servicios'
    | '/administracion/monitoreo/weather'
    | '/tesoreria/pagar/eventuales'
    | '/tesoreria/pagar/mensuales'
    | '/tesoreria/pagar/proveedores'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/produccion'
    | '/tesoreria'
    | '/administracion/activos'
    | '/almacen/catalogos'
    | '/almacen/ingresos'
    | '/almacen/salidas'
    | '/almacen/stock'
    | '/contabilidad/compras'
    | '/contabilidad/ventas'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/cotizaciones'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/produccion/stock'
    | '/tesoreria/cobrar'
    | '/administracion/'
    | '/almacen/'
    | '/contabilidad/'
    | '/gerencia/'
    | '/produccion/'
    | '/tesoreria/'
    | '/administracion/monitoreo'
    | '/administracion/monitoreo/_layout'
    | '/tesoreria/pagar'
    | '/tesoreria/pagar/_layout'
    | '/administracion/historial/compras'
    | '/administracion/historial/indez'
    | '/administracion/historial/ventas'
    | '/administracion/lista/clientes'
    | '/administracion/lista/proveedores'
    | '/gerencia/cotizaciones/crear'
    | '/tesoreria/movimiento/caja'
    | '/tesoreria/movimiento/dolares'
    | '/tesoreria/movimiento/soles'
    | '/administracion/monitoreo/'
    | '/tesoreria/pagar/'
    | '/administracion/lista/'
    | '/gerencia/cotizaciones/'
    | '/tesoreria/movimiento/'
    | '/administracion/monitoreo/_layout/chips'
    | '/administracion/monitoreo/_layout/inicio'
    | '/administracion/monitoreo/_layout/pro'
    | '/administracion/monitoreo/_layout/servicios'
    | '/administracion/monitoreo/_layout/weather'
    | '/tesoreria/pagar/_layout/eventuales'
    | '/tesoreria/pagar/_layout/mensuales'
    | '/tesoreria/pagar/_layout/proveedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdministracionRoute: typeof AdministracionRouteWithChildren
  AlmacenRoute: typeof AlmacenRouteWithChildren
  ContabilidadRoute: typeof ContabilidadRouteWithChildren
  GerenciaRoute: typeof GerenciaRouteWithChildren
  ProduccionRoute: typeof ProduccionRouteWithChildren
  TesoreriaRoute: typeof TesoreriaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tesoreria': {
      id: '/tesoreria'
      path: '/tesoreria'
      fullPath: '/tesoreria'
      preLoaderRoute: typeof TesoreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad': {
      id: '/contabilidad'
      path: '/contabilidad'
      fullPath: '/contabilidad'
      preLoaderRoute: typeof ContabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacen': {
      id: '/almacen'
      path: '/almacen'
      fullPath: '/almacen'
      preLoaderRoute: typeof AlmacenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoreria/pagar': {
      id: '/tesoreria/pagar'
      path: '/pagar'
      fullPath: '/tesoreria/pagar'
      preLoaderRoute: typeof TesoreriaPagarRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/administracion/monitoreo': {
      id: '/administracion/monitoreo'
      path: '/monitoreo'
      fullPath: '/administracion/monitoreo'
      preLoaderRoute: typeof AdministracionMonitoreoRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/tesoreria/': {
      id: '/tesoreria/'
      path: '/'
      fullPath: '/tesoreria/'
      preLoaderRoute: typeof TesoreriaIndexLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/produccion/': {
      id: '/produccion/'
      path: '/'
      fullPath: '/produccion/'
      preLoaderRoute: typeof ProduccionIndexLazyRouteImport
      parentRoute: typeof ProduccionRoute
    }
    '/gerencia/': {
      id: '/gerencia/'
      path: '/'
      fullPath: '/gerencia/'
      preLoaderRoute: typeof GerenciaIndexLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/contabilidad/': {
      id: '/contabilidad/'
      path: '/'
      fullPath: '/contabilidad/'
      preLoaderRoute: typeof ContabilidadIndexLazyRouteImport
      parentRoute: typeof ContabilidadRoute
    }
    '/almacen/': {
      id: '/almacen/'
      path: '/'
      fullPath: '/almacen/'
      preLoaderRoute: typeof AlmacenIndexLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/tesoreria/cobrar': {
      id: '/tesoreria/cobrar'
      path: '/cobrar'
      fullPath: '/tesoreria/cobrar'
      preLoaderRoute: typeof TesoreriaCobrarLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/produccion/stock': {
      id: '/produccion/stock'
      path: '/stock'
      fullPath: '/produccion/stock'
      preLoaderRoute: typeof ProduccionStockLazyRouteImport
      parentRoute: typeof ProduccionRoute
    }
    '/gerencia/usuarios': {
      id: '/gerencia/usuarios'
      path: '/usuarios'
      fullPath: '/gerencia/usuarios'
      preLoaderRoute: typeof GerenciaUsuariosLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/ordenes': {
      id: '/gerencia/ordenes'
      path: '/ordenes'
      fullPath: '/gerencia/ordenes'
      preLoaderRoute: typeof GerenciaOrdenesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/cotizaciones': {
      id: '/gerencia/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/gerencia/cotizaciones'
      preLoaderRoute: typeof GerenciaCotizacionesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/activos': {
      id: '/gerencia/activos'
      path: '/activos'
      fullPath: '/gerencia/activos'
      preLoaderRoute: typeof GerenciaActivosLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/actividades': {
      id: '/gerencia/actividades'
      path: '/actividades'
      fullPath: '/gerencia/actividades'
      preLoaderRoute: typeof GerenciaActividadesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/contabilidad/ventas': {
      id: '/contabilidad/ventas'
      path: '/ventas'
      fullPath: '/contabilidad/ventas'
      preLoaderRoute: typeof ContabilidadVentasLazyRouteImport
      parentRoute: typeof ContabilidadRoute
    }
    '/contabilidad/compras': {
      id: '/contabilidad/compras'
      path: '/compras'
      fullPath: '/contabilidad/compras'
      preLoaderRoute: typeof ContabilidadComprasLazyRouteImport
      parentRoute: typeof ContabilidadRoute
    }
    '/almacen/stock': {
      id: '/almacen/stock'
      path: '/stock'
      fullPath: '/almacen/stock'
      preLoaderRoute: typeof AlmacenStockLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/salidas': {
      id: '/almacen/salidas'
      path: '/salidas'
      fullPath: '/almacen/salidas'
      preLoaderRoute: typeof AlmacenSalidasLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/ingresos': {
      id: '/almacen/ingresos'
      path: '/ingresos'
      fullPath: '/almacen/ingresos'
      preLoaderRoute: typeof AlmacenIngresosLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/almacen/catalogos': {
      id: '/almacen/catalogos'
      path: '/catalogos'
      fullPath: '/almacen/catalogos'
      preLoaderRoute: typeof AlmacenCatalogosLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/administracion/activos': {
      id: '/administracion/activos'
      path: '/activos'
      fullPath: '/administracion/activos'
      preLoaderRoute: typeof AdministracionActivosLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/tesoreria/movimiento/': {
      id: '/tesoreria/movimiento/'
      path: '/movimiento'
      fullPath: '/tesoreria/movimiento'
      preLoaderRoute: typeof TesoreriaMovimientoIndexLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/gerencia/cotizaciones/': {
      id: '/gerencia/cotizaciones/'
      path: '/'
      fullPath: '/gerencia/cotizaciones/'
      preLoaderRoute: typeof GerenciaCotizacionesIndexLazyRouteImport
      parentRoute: typeof GerenciaCotizacionesLazyRoute
    }
    '/administracion/lista/': {
      id: '/administracion/lista/'
      path: '/lista'
      fullPath: '/administracion/lista'
      preLoaderRoute: typeof AdministracionListaIndexLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/tesoreria/pagar/': {
      id: '/tesoreria/pagar/'
      path: '/'
      fullPath: '/tesoreria/pagar/'
      preLoaderRoute: typeof TesoreriaPagarIndexRouteImport
      parentRoute: typeof TesoreriaPagarRoute
    }
    '/administracion/monitoreo/': {
      id: '/administracion/monitoreo/'
      path: '/'
      fullPath: '/administracion/monitoreo/'
      preLoaderRoute: typeof AdministracionMonitoreoIndexRouteImport
      parentRoute: typeof AdministracionMonitoreoRoute
    }
    '/tesoreria/movimiento/soles': {
      id: '/tesoreria/movimiento/soles'
      path: '/movimiento/soles'
      fullPath: '/tesoreria/movimiento/soles'
      preLoaderRoute: typeof TesoreriaMovimientoSolesLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/tesoreria/movimiento/dolares': {
      id: '/tesoreria/movimiento/dolares'
      path: '/movimiento/dolares'
      fullPath: '/tesoreria/movimiento/dolares'
      preLoaderRoute: typeof TesoreriaMovimientoDolaresLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/tesoreria/movimiento/caja': {
      id: '/tesoreria/movimiento/caja'
      path: '/movimiento/caja'
      fullPath: '/tesoreria/movimiento/caja'
      preLoaderRoute: typeof TesoreriaMovimientoCajaLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/gerencia/cotizaciones/crear': {
      id: '/gerencia/cotizaciones/crear'
      path: '/crear'
      fullPath: '/gerencia/cotizaciones/crear'
      preLoaderRoute: typeof GerenciaCotizacionesCrearLazyRouteImport
      parentRoute: typeof GerenciaCotizacionesLazyRoute
    }
    '/administracion/lista/proveedores': {
      id: '/administracion/lista/proveedores'
      path: '/lista/proveedores'
      fullPath: '/administracion/lista/proveedores'
      preLoaderRoute: typeof AdministracionListaProveedoresLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/lista/clientes': {
      id: '/administracion/lista/clientes'
      path: '/lista/clientes'
      fullPath: '/administracion/lista/clientes'
      preLoaderRoute: typeof AdministracionListaClientesLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/historial/ventas': {
      id: '/administracion/historial/ventas'
      path: '/historial/ventas'
      fullPath: '/administracion/historial/ventas'
      preLoaderRoute: typeof AdministracionHistorialVentasLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/historial/indez': {
      id: '/administracion/historial/indez'
      path: '/historial/indez'
      fullPath: '/administracion/historial/indez'
      preLoaderRoute: typeof AdministracionHistorialIndezLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/historial/compras': {
      id: '/administracion/historial/compras'
      path: '/historial/compras'
      fullPath: '/administracion/historial/compras'
      preLoaderRoute: typeof AdministracionHistorialComprasLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/tesoreria/pagar/_layout': {
      id: '/tesoreria/pagar/_layout'
      path: '/pagar'
      fullPath: '/tesoreria/pagar'
      preLoaderRoute: typeof TesoreriaPagarLayoutRouteImport
      parentRoute: typeof TesoreriaPagarRoute
    }
    '/administracion/monitoreo/_layout': {
      id: '/administracion/monitoreo/_layout'
      path: '/monitoreo'
      fullPath: '/administracion/monitoreo'
      preLoaderRoute: typeof AdministracionMonitoreoLayoutRouteImport
      parentRoute: typeof AdministracionMonitoreoRoute
    }
    '/tesoreria/pagar/_layout/proveedores': {
      id: '/tesoreria/pagar/_layout/proveedores'
      path: '/proveedores'
      fullPath: '/tesoreria/pagar/proveedores'
      preLoaderRoute: typeof TesoreriaPagarLayoutProveedoresRouteImport
      parentRoute: typeof TesoreriaPagarLayoutRoute
    }
    '/tesoreria/pagar/_layout/mensuales': {
      id: '/tesoreria/pagar/_layout/mensuales'
      path: '/mensuales'
      fullPath: '/tesoreria/pagar/mensuales'
      preLoaderRoute: typeof TesoreriaPagarLayoutMensualesRouteImport
      parentRoute: typeof TesoreriaPagarLayoutRoute
    }
    '/tesoreria/pagar/_layout/eventuales': {
      id: '/tesoreria/pagar/_layout/eventuales'
      path: '/eventuales'
      fullPath: '/tesoreria/pagar/eventuales'
      preLoaderRoute: typeof TesoreriaPagarLayoutEventualesRouteImport
      parentRoute: typeof TesoreriaPagarLayoutRoute
    }
    '/administracion/monitoreo/_layout/weather': {
      id: '/administracion/monitoreo/_layout/weather'
      path: '/weather'
      fullPath: '/administracion/monitoreo/weather'
      preLoaderRoute: typeof AdministracionMonitoreoLayoutWeatherRouteImport
      parentRoute: typeof AdministracionMonitoreoLayoutRoute
    }
    '/administracion/monitoreo/_layout/servicios': {
      id: '/administracion/monitoreo/_layout/servicios'
      path: '/servicios'
      fullPath: '/administracion/monitoreo/servicios'
      preLoaderRoute: typeof AdministracionMonitoreoLayoutServiciosRouteImport
      parentRoute: typeof AdministracionMonitoreoLayoutRoute
    }
    '/administracion/monitoreo/_layout/pro': {
      id: '/administracion/monitoreo/_layout/pro'
      path: '/pro'
      fullPath: '/administracion/monitoreo/pro'
      preLoaderRoute: typeof AdministracionMonitoreoLayoutProRouteImport
      parentRoute: typeof AdministracionMonitoreoLayoutRoute
    }
    '/administracion/monitoreo/_layout/inicio': {
      id: '/administracion/monitoreo/_layout/inicio'
      path: '/inicio'
      fullPath: '/administracion/monitoreo/inicio'
      preLoaderRoute: typeof AdministracionMonitoreoLayoutInicioRouteImport
      parentRoute: typeof AdministracionMonitoreoLayoutRoute
    }
    '/administracion/monitoreo/_layout/chips': {
      id: '/administracion/monitoreo/_layout/chips'
      path: '/chips'
      fullPath: '/administracion/monitoreo/chips'
      preLoaderRoute: typeof AdministracionMonitoreoLayoutChipsRouteImport
      parentRoute: typeof AdministracionMonitoreoLayoutRoute
    }
  }
}

interface AdministracionMonitoreoLayoutRouteChildren {
  AdministracionMonitoreoLayoutChipsRoute: typeof AdministracionMonitoreoLayoutChipsRoute
  AdministracionMonitoreoLayoutInicioRoute: typeof AdministracionMonitoreoLayoutInicioRoute
  AdministracionMonitoreoLayoutProRoute: typeof AdministracionMonitoreoLayoutProRoute
  AdministracionMonitoreoLayoutServiciosRoute: typeof AdministracionMonitoreoLayoutServiciosRoute
  AdministracionMonitoreoLayoutWeatherRoute: typeof AdministracionMonitoreoLayoutWeatherRoute
}

const AdministracionMonitoreoLayoutRouteChildren: AdministracionMonitoreoLayoutRouteChildren =
  {
    AdministracionMonitoreoLayoutChipsRoute:
      AdministracionMonitoreoLayoutChipsRoute,
    AdministracionMonitoreoLayoutInicioRoute:
      AdministracionMonitoreoLayoutInicioRoute,
    AdministracionMonitoreoLayoutProRoute:
      AdministracionMonitoreoLayoutProRoute,
    AdministracionMonitoreoLayoutServiciosRoute:
      AdministracionMonitoreoLayoutServiciosRoute,
    AdministracionMonitoreoLayoutWeatherRoute:
      AdministracionMonitoreoLayoutWeatherRoute,
  }

const AdministracionMonitoreoLayoutRouteWithChildren =
  AdministracionMonitoreoLayoutRoute._addFileChildren(
    AdministracionMonitoreoLayoutRouteChildren,
  )

interface AdministracionMonitoreoRouteChildren {
  AdministracionMonitoreoLayoutRoute: typeof AdministracionMonitoreoLayoutRouteWithChildren
  AdministracionMonitoreoIndexRoute: typeof AdministracionMonitoreoIndexRoute
}

const AdministracionMonitoreoRouteChildren: AdministracionMonitoreoRouteChildren =
  {
    AdministracionMonitoreoLayoutRoute:
      AdministracionMonitoreoLayoutRouteWithChildren,
    AdministracionMonitoreoIndexRoute: AdministracionMonitoreoIndexRoute,
  }

const AdministracionMonitoreoRouteWithChildren =
  AdministracionMonitoreoRoute._addFileChildren(
    AdministracionMonitoreoRouteChildren,
  )

interface AdministracionRouteChildren {
  AdministracionActivosLazyRoute: typeof AdministracionActivosLazyRoute
  AdministracionIndexLazyRoute: typeof AdministracionIndexLazyRoute
  AdministracionMonitoreoRoute: typeof AdministracionMonitoreoRouteWithChildren
  AdministracionHistorialComprasLazyRoute: typeof AdministracionHistorialComprasLazyRoute
  AdministracionHistorialIndezLazyRoute: typeof AdministracionHistorialIndezLazyRoute
  AdministracionHistorialVentasLazyRoute: typeof AdministracionHistorialVentasLazyRoute
  AdministracionListaClientesLazyRoute: typeof AdministracionListaClientesLazyRoute
  AdministracionListaProveedoresLazyRoute: typeof AdministracionListaProveedoresLazyRoute
  AdministracionListaIndexLazyRoute: typeof AdministracionListaIndexLazyRoute
}

const AdministracionRouteChildren: AdministracionRouteChildren = {
  AdministracionActivosLazyRoute: AdministracionActivosLazyRoute,
  AdministracionIndexLazyRoute: AdministracionIndexLazyRoute,
  AdministracionMonitoreoRoute: AdministracionMonitoreoRouteWithChildren,
  AdministracionHistorialComprasLazyRoute:
    AdministracionHistorialComprasLazyRoute,
  AdministracionHistorialIndezLazyRoute: AdministracionHistorialIndezLazyRoute,
  AdministracionHistorialVentasLazyRoute:
    AdministracionHistorialVentasLazyRoute,
  AdministracionListaClientesLazyRoute: AdministracionListaClientesLazyRoute,
  AdministracionListaProveedoresLazyRoute:
    AdministracionListaProveedoresLazyRoute,
  AdministracionListaIndexLazyRoute: AdministracionListaIndexLazyRoute,
}

const AdministracionRouteWithChildren = AdministracionRoute._addFileChildren(
  AdministracionRouteChildren,
)

interface AlmacenRouteChildren {
  AlmacenCatalogosLazyRoute: typeof AlmacenCatalogosLazyRoute
  AlmacenIngresosLazyRoute: typeof AlmacenIngresosLazyRoute
  AlmacenSalidasLazyRoute: typeof AlmacenSalidasLazyRoute
  AlmacenStockLazyRoute: typeof AlmacenStockLazyRoute
  AlmacenIndexLazyRoute: typeof AlmacenIndexLazyRoute
}

const AlmacenRouteChildren: AlmacenRouteChildren = {
  AlmacenCatalogosLazyRoute: AlmacenCatalogosLazyRoute,
  AlmacenIngresosLazyRoute: AlmacenIngresosLazyRoute,
  AlmacenSalidasLazyRoute: AlmacenSalidasLazyRoute,
  AlmacenStockLazyRoute: AlmacenStockLazyRoute,
  AlmacenIndexLazyRoute: AlmacenIndexLazyRoute,
}

const AlmacenRouteWithChildren =
  AlmacenRoute._addFileChildren(AlmacenRouteChildren)

interface ContabilidadRouteChildren {
  ContabilidadComprasLazyRoute: typeof ContabilidadComprasLazyRoute
  ContabilidadVentasLazyRoute: typeof ContabilidadVentasLazyRoute
  ContabilidadIndexLazyRoute: typeof ContabilidadIndexLazyRoute
}

const ContabilidadRouteChildren: ContabilidadRouteChildren = {
  ContabilidadComprasLazyRoute: ContabilidadComprasLazyRoute,
  ContabilidadVentasLazyRoute: ContabilidadVentasLazyRoute,
  ContabilidadIndexLazyRoute: ContabilidadIndexLazyRoute,
}

const ContabilidadRouteWithChildren = ContabilidadRoute._addFileChildren(
  ContabilidadRouteChildren,
)

interface GerenciaCotizacionesLazyRouteChildren {
  GerenciaCotizacionesCrearLazyRoute: typeof GerenciaCotizacionesCrearLazyRoute
  GerenciaCotizacionesIndexLazyRoute: typeof GerenciaCotizacionesIndexLazyRoute
}

const GerenciaCotizacionesLazyRouteChildren: GerenciaCotizacionesLazyRouteChildren =
  {
    GerenciaCotizacionesCrearLazyRoute: GerenciaCotizacionesCrearLazyRoute,
    GerenciaCotizacionesIndexLazyRoute: GerenciaCotizacionesIndexLazyRoute,
  }

const GerenciaCotizacionesLazyRouteWithChildren =
  GerenciaCotizacionesLazyRoute._addFileChildren(
    GerenciaCotizacionesLazyRouteChildren,
  )

interface GerenciaRouteChildren {
  GerenciaActividadesLazyRoute: typeof GerenciaActividadesLazyRoute
  GerenciaActivosLazyRoute: typeof GerenciaActivosLazyRoute
  GerenciaCotizacionesLazyRoute: typeof GerenciaCotizacionesLazyRouteWithChildren
  GerenciaOrdenesLazyRoute: typeof GerenciaOrdenesLazyRoute
  GerenciaUsuariosLazyRoute: typeof GerenciaUsuariosLazyRoute
  GerenciaIndexLazyRoute: typeof GerenciaIndexLazyRoute
}

const GerenciaRouteChildren: GerenciaRouteChildren = {
  GerenciaActividadesLazyRoute: GerenciaActividadesLazyRoute,
  GerenciaActivosLazyRoute: GerenciaActivosLazyRoute,
  GerenciaCotizacionesLazyRoute: GerenciaCotizacionesLazyRouteWithChildren,
  GerenciaOrdenesLazyRoute: GerenciaOrdenesLazyRoute,
  GerenciaUsuariosLazyRoute: GerenciaUsuariosLazyRoute,
  GerenciaIndexLazyRoute: GerenciaIndexLazyRoute,
}

const GerenciaRouteWithChildren = GerenciaRoute._addFileChildren(
  GerenciaRouteChildren,
)

interface ProduccionRouteChildren {
  ProduccionStockLazyRoute: typeof ProduccionStockLazyRoute
  ProduccionIndexLazyRoute: typeof ProduccionIndexLazyRoute
}

const ProduccionRouteChildren: ProduccionRouteChildren = {
  ProduccionStockLazyRoute: ProduccionStockLazyRoute,
  ProduccionIndexLazyRoute: ProduccionIndexLazyRoute,
}

const ProduccionRouteWithChildren = ProduccionRoute._addFileChildren(
  ProduccionRouteChildren,
)

interface TesoreriaPagarLayoutRouteChildren {
  TesoreriaPagarLayoutEventualesRoute: typeof TesoreriaPagarLayoutEventualesRoute
  TesoreriaPagarLayoutMensualesRoute: typeof TesoreriaPagarLayoutMensualesRoute
  TesoreriaPagarLayoutProveedoresRoute: typeof TesoreriaPagarLayoutProveedoresRoute
}

const TesoreriaPagarLayoutRouteChildren: TesoreriaPagarLayoutRouteChildren = {
  TesoreriaPagarLayoutEventualesRoute: TesoreriaPagarLayoutEventualesRoute,
  TesoreriaPagarLayoutMensualesRoute: TesoreriaPagarLayoutMensualesRoute,
  TesoreriaPagarLayoutProveedoresRoute: TesoreriaPagarLayoutProveedoresRoute,
}

const TesoreriaPagarLayoutRouteWithChildren =
  TesoreriaPagarLayoutRoute._addFileChildren(TesoreriaPagarLayoutRouteChildren)

interface TesoreriaPagarRouteChildren {
  TesoreriaPagarLayoutRoute: typeof TesoreriaPagarLayoutRouteWithChildren
  TesoreriaPagarIndexRoute: typeof TesoreriaPagarIndexRoute
}

const TesoreriaPagarRouteChildren: TesoreriaPagarRouteChildren = {
  TesoreriaPagarLayoutRoute: TesoreriaPagarLayoutRouteWithChildren,
  TesoreriaPagarIndexRoute: TesoreriaPagarIndexRoute,
}

const TesoreriaPagarRouteWithChildren = TesoreriaPagarRoute._addFileChildren(
  TesoreriaPagarRouteChildren,
)

interface TesoreriaRouteChildren {
  TesoreriaCobrarLazyRoute: typeof TesoreriaCobrarLazyRoute
  TesoreriaIndexLazyRoute: typeof TesoreriaIndexLazyRoute
  TesoreriaPagarRoute: typeof TesoreriaPagarRouteWithChildren
  TesoreriaMovimientoCajaLazyRoute: typeof TesoreriaMovimientoCajaLazyRoute
  TesoreriaMovimientoDolaresLazyRoute: typeof TesoreriaMovimientoDolaresLazyRoute
  TesoreriaMovimientoSolesLazyRoute: typeof TesoreriaMovimientoSolesLazyRoute
  TesoreriaMovimientoIndexLazyRoute: typeof TesoreriaMovimientoIndexLazyRoute
}

const TesoreriaRouteChildren: TesoreriaRouteChildren = {
  TesoreriaCobrarLazyRoute: TesoreriaCobrarLazyRoute,
  TesoreriaIndexLazyRoute: TesoreriaIndexLazyRoute,
  TesoreriaPagarRoute: TesoreriaPagarRouteWithChildren,
  TesoreriaMovimientoCajaLazyRoute: TesoreriaMovimientoCajaLazyRoute,
  TesoreriaMovimientoDolaresLazyRoute: TesoreriaMovimientoDolaresLazyRoute,
  TesoreriaMovimientoSolesLazyRoute: TesoreriaMovimientoSolesLazyRoute,
  TesoreriaMovimientoIndexLazyRoute: TesoreriaMovimientoIndexLazyRoute,
}

const TesoreriaRouteWithChildren = TesoreriaRoute._addFileChildren(
  TesoreriaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdministracionRoute: AdministracionRouteWithChildren,
  AlmacenRoute: AlmacenRouteWithChildren,
  ContabilidadRoute: ContabilidadRouteWithChildren,
  GerenciaRoute: GerenciaRouteWithChildren,
  ProduccionRoute: ProduccionRouteWithChildren,
  TesoreriaRoute: TesoreriaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
