/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesoreriaRouteImport } from './routes/tesoreria'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as ContabilidadRouteImport } from './routes/contabilidad'
import { Route as AlmacenRouteImport } from './routes/almacen'
import { Route as AdministracionRouteImport } from './routes/administracion'

const IndexLazyRouteImport = createFileRoute('/')()
const TesoreriaIndexLazyRouteImport = createFileRoute('/tesoreria/')()
const GerenciaIndexLazyRouteImport = createFileRoute('/gerencia/')()
const ContabilidadIndexLazyRouteImport = createFileRoute('/contabilidad/')()
const AlmacenIndexLazyRouteImport = createFileRoute('/almacen/')()
const AdministracionIndexLazyRouteImport = createFileRoute('/administracion/')()
const GerenciaUsuariosLazyRouteImport = createFileRoute('/gerencia/usuarios')()
const GerenciaOrdenesLazyRouteImport = createFileRoute('/gerencia/ordenes')()
const GerenciaCotizacionesLazyRouteImport = createFileRoute(
  '/gerencia/cotizaciones',
)()
const GerenciaActivosLazyRouteImport = createFileRoute('/gerencia/activos')()
const GerenciaActividadesLazyRouteImport = createFileRoute(
  '/gerencia/actividades',
)()
const AdministracionMonitoreoIndexLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/',
)()
const AdministracionMonitoreoWeatherLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/weather',
)()
const AdministracionMonitoreoProLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/pro',
)()
const AdministracionMonitoreoInicioLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/inicio',
)()
const AdministracionMonitoreoChipsLazyRouteImport = createFileRoute(
  '/administracion/monitoreo/chips',
)()

const TesoreriaRoute = TesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadRoute = ContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmacenRoute = AlmacenRouteImport.update({
  id: '/almacen',
  path: '/almacen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracionRoute = AdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TesoreriaIndexLazyRoute = TesoreriaIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TesoreriaRoute,
} as any).lazy(() =>
  import('./routes/tesoreria/index.lazy').then((d) => d.Route),
)
const GerenciaIndexLazyRoute = GerenciaIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/index.lazy').then((d) => d.Route),
)
const ContabilidadIndexLazyRoute = ContabilidadIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContabilidadRoute,
} as any).lazy(() =>
  import('./routes/contabilidad/index.lazy').then((d) => d.Route),
)
const AlmacenIndexLazyRoute = AlmacenIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlmacenRoute,
} as any).lazy(() => import('./routes/almacen/index.lazy').then((d) => d.Route))
const AdministracionIndexLazyRoute = AdministracionIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministracionRoute,
} as any).lazy(() =>
  import('./routes/administracion/index.lazy').then((d) => d.Route),
)
const GerenciaUsuariosLazyRoute = GerenciaUsuariosLazyRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/usuarios.lazy').then((d) => d.Route),
)
const GerenciaOrdenesLazyRoute = GerenciaOrdenesLazyRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/ordenes.lazy').then((d) => d.Route),
)
const GerenciaCotizacionesLazyRoute =
  GerenciaCotizacionesLazyRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => GerenciaRoute,
  } as any).lazy(() =>
    import('./routes/gerencia/cotizaciones.lazy').then((d) => d.Route),
  )
const GerenciaActivosLazyRoute = GerenciaActivosLazyRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/activos.lazy').then((d) => d.Route),
)
const GerenciaActividadesLazyRoute = GerenciaActividadesLazyRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => GerenciaRoute,
} as any).lazy(() =>
  import('./routes/gerencia/actividades.lazy').then((d) => d.Route),
)
const AdministracionMonitoreoIndexLazyRoute =
  AdministracionMonitoreoIndexLazyRouteImport.update({
    id: '/monitoreo/',
    path: '/monitoreo/',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/index.lazy').then((d) => d.Route),
  )
const AdministracionMonitoreoWeatherLazyRoute =
  AdministracionMonitoreoWeatherLazyRouteImport.update({
    id: '/monitoreo/weather',
    path: '/monitoreo/weather',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/weather.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionMonitoreoProLazyRoute =
  AdministracionMonitoreoProLazyRouteImport.update({
    id: '/monitoreo/pro',
    path: '/monitoreo/pro',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/pro.lazy').then((d) => d.Route),
  )
const AdministracionMonitoreoInicioLazyRoute =
  AdministracionMonitoreoInicioLazyRouteImport.update({
    id: '/monitoreo/inicio',
    path: '/monitoreo/inicio',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/inicio.lazy').then(
      (d) => d.Route,
    ),
  )
const AdministracionMonitoreoChipsLazyRoute =
  AdministracionMonitoreoChipsLazyRouteImport.update({
    id: '/monitoreo/chips',
    path: '/monitoreo/chips',
    getParentRoute: () => AdministracionRoute,
  } as any).lazy(() =>
    import('./routes/administracion/monitoreo/chips.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/almacen': typeof AlmacenRouteWithChildren
  '/contabilidad': typeof ContabilidadRouteWithChildren
  '/gerencia': typeof GerenciaRouteWithChildren
  '/tesoreria': typeof TesoreriaRouteWithChildren
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesLazyRoute
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/administracion/': typeof AdministracionIndexLazyRoute
  '/almacen/': typeof AlmacenIndexLazyRoute
  '/contabilidad/': typeof ContabilidadIndexLazyRoute
  '/gerencia/': typeof GerenciaIndexLazyRoute
  '/tesoreria/': typeof TesoreriaIndexLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoChipsLazyRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoInicioLazyRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoProLazyRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoWeatherLazyRoute
  '/administracion/monitoreo': typeof AdministracionMonitoreoIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesLazyRoute
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/administracion': typeof AdministracionIndexLazyRoute
  '/almacen': typeof AlmacenIndexLazyRoute
  '/contabilidad': typeof ContabilidadIndexLazyRoute
  '/gerencia': typeof GerenciaIndexLazyRoute
  '/tesoreria': typeof TesoreriaIndexLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoChipsLazyRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoInicioLazyRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoProLazyRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoWeatherLazyRoute
  '/administracion/monitoreo': typeof AdministracionMonitoreoIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/administracion': typeof AdministracionRouteWithChildren
  '/almacen': typeof AlmacenRouteWithChildren
  '/contabilidad': typeof ContabilidadRouteWithChildren
  '/gerencia': typeof GerenciaRouteWithChildren
  '/tesoreria': typeof TesoreriaRouteWithChildren
  '/gerencia/actividades': typeof GerenciaActividadesLazyRoute
  '/gerencia/activos': typeof GerenciaActivosLazyRoute
  '/gerencia/cotizaciones': typeof GerenciaCotizacionesLazyRoute
  '/gerencia/ordenes': typeof GerenciaOrdenesLazyRoute
  '/gerencia/usuarios': typeof GerenciaUsuariosLazyRoute
  '/administracion/': typeof AdministracionIndexLazyRoute
  '/almacen/': typeof AlmacenIndexLazyRoute
  '/contabilidad/': typeof ContabilidadIndexLazyRoute
  '/gerencia/': typeof GerenciaIndexLazyRoute
  '/tesoreria/': typeof TesoreriaIndexLazyRoute
  '/administracion/monitoreo/chips': typeof AdministracionMonitoreoChipsLazyRoute
  '/administracion/monitoreo/inicio': typeof AdministracionMonitoreoInicioLazyRoute
  '/administracion/monitoreo/pro': typeof AdministracionMonitoreoProLazyRoute
  '/administracion/monitoreo/weather': typeof AdministracionMonitoreoWeatherLazyRoute
  '/administracion/monitoreo/': typeof AdministracionMonitoreoIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/tesoreria'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/cotizaciones'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/administracion/'
    | '/almacen/'
    | '/contabilidad/'
    | '/gerencia/'
    | '/tesoreria/'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/weather'
    | '/administracion/monitoreo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/cotizaciones'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/tesoreria'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/weather'
    | '/administracion/monitoreo'
  id:
    | '__root__'
    | '/'
    | '/administracion'
    | '/almacen'
    | '/contabilidad'
    | '/gerencia'
    | '/tesoreria'
    | '/gerencia/actividades'
    | '/gerencia/activos'
    | '/gerencia/cotizaciones'
    | '/gerencia/ordenes'
    | '/gerencia/usuarios'
    | '/administracion/'
    | '/almacen/'
    | '/contabilidad/'
    | '/gerencia/'
    | '/tesoreria/'
    | '/administracion/monitoreo/chips'
    | '/administracion/monitoreo/inicio'
    | '/administracion/monitoreo/pro'
    | '/administracion/monitoreo/weather'
    | '/administracion/monitoreo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdministracionRoute: typeof AdministracionRouteWithChildren
  AlmacenRoute: typeof AlmacenRouteWithChildren
  ContabilidadRoute: typeof ContabilidadRouteWithChildren
  GerenciaRoute: typeof GerenciaRouteWithChildren
  TesoreriaRoute: typeof TesoreriaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tesoreria': {
      id: '/tesoreria'
      path: '/tesoreria'
      fullPath: '/tesoreria'
      preLoaderRoute: typeof TesoreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad': {
      id: '/contabilidad'
      path: '/contabilidad'
      fullPath: '/contabilidad'
      preLoaderRoute: typeof ContabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almacen': {
      id: '/almacen'
      path: '/almacen'
      fullPath: '/almacen'
      preLoaderRoute: typeof AlmacenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracion': {
      id: '/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AdministracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoreria/': {
      id: '/tesoreria/'
      path: '/'
      fullPath: '/tesoreria/'
      preLoaderRoute: typeof TesoreriaIndexLazyRouteImport
      parentRoute: typeof TesoreriaRoute
    }
    '/gerencia/': {
      id: '/gerencia/'
      path: '/'
      fullPath: '/gerencia/'
      preLoaderRoute: typeof GerenciaIndexLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/contabilidad/': {
      id: '/contabilidad/'
      path: '/'
      fullPath: '/contabilidad/'
      preLoaderRoute: typeof ContabilidadIndexLazyRouteImport
      parentRoute: typeof ContabilidadRoute
    }
    '/almacen/': {
      id: '/almacen/'
      path: '/'
      fullPath: '/almacen/'
      preLoaderRoute: typeof AlmacenIndexLazyRouteImport
      parentRoute: typeof AlmacenRoute
    }
    '/administracion/': {
      id: '/administracion/'
      path: '/'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AdministracionIndexLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/gerencia/usuarios': {
      id: '/gerencia/usuarios'
      path: '/usuarios'
      fullPath: '/gerencia/usuarios'
      preLoaderRoute: typeof GerenciaUsuariosLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/ordenes': {
      id: '/gerencia/ordenes'
      path: '/ordenes'
      fullPath: '/gerencia/ordenes'
      preLoaderRoute: typeof GerenciaOrdenesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/cotizaciones': {
      id: '/gerencia/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/gerencia/cotizaciones'
      preLoaderRoute: typeof GerenciaCotizacionesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/activos': {
      id: '/gerencia/activos'
      path: '/activos'
      fullPath: '/gerencia/activos'
      preLoaderRoute: typeof GerenciaActivosLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/gerencia/actividades': {
      id: '/gerencia/actividades'
      path: '/actividades'
      fullPath: '/gerencia/actividades'
      preLoaderRoute: typeof GerenciaActividadesLazyRouteImport
      parentRoute: typeof GerenciaRoute
    }
    '/administracion/monitoreo/': {
      id: '/administracion/monitoreo/'
      path: '/monitoreo'
      fullPath: '/administracion/monitoreo'
      preLoaderRoute: typeof AdministracionMonitoreoIndexLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/weather': {
      id: '/administracion/monitoreo/weather'
      path: '/monitoreo/weather'
      fullPath: '/administracion/monitoreo/weather'
      preLoaderRoute: typeof AdministracionMonitoreoWeatherLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/pro': {
      id: '/administracion/monitoreo/pro'
      path: '/monitoreo/pro'
      fullPath: '/administracion/monitoreo/pro'
      preLoaderRoute: typeof AdministracionMonitoreoProLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/inicio': {
      id: '/administracion/monitoreo/inicio'
      path: '/monitoreo/inicio'
      fullPath: '/administracion/monitoreo/inicio'
      preLoaderRoute: typeof AdministracionMonitoreoInicioLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
    '/administracion/monitoreo/chips': {
      id: '/administracion/monitoreo/chips'
      path: '/monitoreo/chips'
      fullPath: '/administracion/monitoreo/chips'
      preLoaderRoute: typeof AdministracionMonitoreoChipsLazyRouteImport
      parentRoute: typeof AdministracionRoute
    }
  }
}

interface AdministracionRouteChildren {
  AdministracionIndexLazyRoute: typeof AdministracionIndexLazyRoute
  AdministracionMonitoreoChipsLazyRoute: typeof AdministracionMonitoreoChipsLazyRoute
  AdministracionMonitoreoInicioLazyRoute: typeof AdministracionMonitoreoInicioLazyRoute
  AdministracionMonitoreoProLazyRoute: typeof AdministracionMonitoreoProLazyRoute
  AdministracionMonitoreoWeatherLazyRoute: typeof AdministracionMonitoreoWeatherLazyRoute
  AdministracionMonitoreoIndexLazyRoute: typeof AdministracionMonitoreoIndexLazyRoute
}

const AdministracionRouteChildren: AdministracionRouteChildren = {
  AdministracionIndexLazyRoute: AdministracionIndexLazyRoute,
  AdministracionMonitoreoChipsLazyRoute: AdministracionMonitoreoChipsLazyRoute,
  AdministracionMonitoreoInicioLazyRoute:
    AdministracionMonitoreoInicioLazyRoute,
  AdministracionMonitoreoProLazyRoute: AdministracionMonitoreoProLazyRoute,
  AdministracionMonitoreoWeatherLazyRoute:
    AdministracionMonitoreoWeatherLazyRoute,
  AdministracionMonitoreoIndexLazyRoute: AdministracionMonitoreoIndexLazyRoute,
}

const AdministracionRouteWithChildren = AdministracionRoute._addFileChildren(
  AdministracionRouteChildren,
)

interface AlmacenRouteChildren {
  AlmacenIndexLazyRoute: typeof AlmacenIndexLazyRoute
}

const AlmacenRouteChildren: AlmacenRouteChildren = {
  AlmacenIndexLazyRoute: AlmacenIndexLazyRoute,
}

const AlmacenRouteWithChildren =
  AlmacenRoute._addFileChildren(AlmacenRouteChildren)

interface ContabilidadRouteChildren {
  ContabilidadIndexLazyRoute: typeof ContabilidadIndexLazyRoute
}

const ContabilidadRouteChildren: ContabilidadRouteChildren = {
  ContabilidadIndexLazyRoute: ContabilidadIndexLazyRoute,
}

const ContabilidadRouteWithChildren = ContabilidadRoute._addFileChildren(
  ContabilidadRouteChildren,
)

interface GerenciaRouteChildren {
  GerenciaActividadesLazyRoute: typeof GerenciaActividadesLazyRoute
  GerenciaActivosLazyRoute: typeof GerenciaActivosLazyRoute
  GerenciaCotizacionesLazyRoute: typeof GerenciaCotizacionesLazyRoute
  GerenciaOrdenesLazyRoute: typeof GerenciaOrdenesLazyRoute
  GerenciaUsuariosLazyRoute: typeof GerenciaUsuariosLazyRoute
  GerenciaIndexLazyRoute: typeof GerenciaIndexLazyRoute
}

const GerenciaRouteChildren: GerenciaRouteChildren = {
  GerenciaActividadesLazyRoute: GerenciaActividadesLazyRoute,
  GerenciaActivosLazyRoute: GerenciaActivosLazyRoute,
  GerenciaCotizacionesLazyRoute: GerenciaCotizacionesLazyRoute,
  GerenciaOrdenesLazyRoute: GerenciaOrdenesLazyRoute,
  GerenciaUsuariosLazyRoute: GerenciaUsuariosLazyRoute,
  GerenciaIndexLazyRoute: GerenciaIndexLazyRoute,
}

const GerenciaRouteWithChildren = GerenciaRoute._addFileChildren(
  GerenciaRouteChildren,
)

interface TesoreriaRouteChildren {
  TesoreriaIndexLazyRoute: typeof TesoreriaIndexLazyRoute
}

const TesoreriaRouteChildren: TesoreriaRouteChildren = {
  TesoreriaIndexLazyRoute: TesoreriaIndexLazyRoute,
}

const TesoreriaRouteWithChildren = TesoreriaRoute._addFileChildren(
  TesoreriaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdministracionRoute: AdministracionRouteWithChildren,
  AlmacenRoute: AlmacenRouteWithChildren,
  ContabilidadRoute: ContabilidadRouteWithChildren,
  GerenciaRoute: GerenciaRouteWithChildren,
  TesoreriaRoute: TesoreriaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
